export interface DailyLessonData {
  dayNumber: number;
  title: string;
  tradingTopic: string;
  tradingLesson: string;
  scriptureReference: string;
  scriptureText: string;
  devotionalMessage: string;
  contentPrompt: string;
  suggestedHashtags: string[];
  mediaType: 'image' | 'video' | 'carousel';
  tokenReward: number;
  bonusTokens: number;
  weekNumber: number;
  category: 'foundation' | 'strategy' | 'mindset' | 'execution' | 'review';
}

export const ambassadorContentCurriculum: DailyLessonData[] = [
  // Week 1: Foundation - Lets Get This Bread
  {
    dayNumber: 1,
    title: "Yo, Your Trading Journey Starts Now",
    tradingTopic: "Introduction to Chart Analysis",
    tradingLesson: "Every trader who made it big started right here - learning to read charts. Today we breaking down candlestick patterns, the building blocks that show you what the market is really doing. No cap, this is where your bag starts.",
    scriptureReference: "Proverbs 24:27",
    scriptureText: "Prepare your work outside; get everything ready for yourself in the field, and after that build your house.",
    devotionalMessage: "Scripture says prep before you build, fam. Same energy in trading - you gotta lay that foundation first. Master the basics and everything else falls into place.",
    contentPrompt: "Drop an inspiring post about starting your trading journey the right way. ASK YOUR AUDIENCE: 'Where are you on your trading journey? Drop a comment!' Include a clear CTA: 'Ready to level up? Try VEDD AI free and get instant chart analysis - link in bio!' Share a screenshot of your first VEDD analysis to show what's possible.",
    suggestedHashtags: ["#TradingJourney", "#ChartGame", "#FaithAndFinance", "#VEDDAi", "#TryVEDDFree"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 2,
    title: "Candlesticks - Reading The Story",
    tradingTopic: "Candlestick Patterns Basics",
    tradingLesson: "Candlesticks be telling stories of bulls and bears throwing hands in the market. Today you learning bullish engulfing, bearish engulfing, and doji patterns - these three right here show you when the market is about to flip or when its straight confused.",
    scriptureReference: "Ecclesiastes 3:1",
    scriptureText: "For everything there is a season, and a time for every matter under heaven.",
    devotionalMessage: "Markets got seasons too - times to buy, times to sell, times to chill. Wisdom is knowing what season youre in. Let these candlestick patterns show you the markets current mood.",
    contentPrompt: "Create a carousel showing the 3 key candlestick patterns with VEDD AI identifying each one. ASK: 'Can you spot these patterns on your charts? Comment which one you see most!' End with: 'Want AI to spot these patterns FOR you? VEDD AI does it in seconds - try it free!' Include your referral link.",
    suggestedHashtags: ["#CandlestickPatterns", "#TradingEducation", "#VEDDAi", "#JoinOurTribe", "#FreeTrial"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 3,
    title: "Support & Resistance - Know Your Zones",
    tradingTopic: "Key Price Levels",
    tradingLesson: "Support and resistance are those invisible walls and floors where price likes to bounce. These levels get created by trader psychology - everyone watching the same spots. Learn to draw these zones and youll see the market way different.",
    scriptureReference: "Psalm 18:2",
    scriptureText: "The Lord is my rock and my fortress and my deliverer, my God, my rock, in whom I take refuge.",
    devotionalMessage: "Just like God is our rock and fortress, support levels protect price from falling further. Understanding where these zones hit gives you that confidence when you taking trades.",
    contentPrompt: "Post a chart screenshot with support/resistance levels marked by VEDD AI. ASK: 'Tag a trading buddy who needs to learn about S/R levels!' Share the rock/fortress metaphor. CTA: 'Stop guessing where levels are - let AI find them for you. DM me 'LEVELS' for a free walkthrough!'",
    suggestedHashtags: ["#SupportResistance", "#VEDDAi", "#TradingCommunity", "#TagAFriend", "#DMmeNow"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 4,
    title: "Trend Is Your Friend - Read The Wave",
    tradingTopic: "Reading Market Direction",
    tradingLesson: "The trend is your homie until the end - dont fight it. Learn to spot uptrends, downtrends, and when the market is just chopping around. Higher highs, higher lows for bulls. Lower highs, lower lows for bears. Simple as that.",
    scriptureReference: "Isaiah 30:21",
    scriptureText: "And your ears shall hear a word behind you, saying, 'This is the way, walk in it,' when you turn to the right or when you turn to the left.",
    devotionalMessage: "God gives direction for our path, and the trend gives direction for our trades. Learning to ride the wave with patience beats fighting the market every time.",
    contentPrompt: "Show a VEDD AI analysis identifying a clear trend. Create a poll: 'Do you trade WITH the trend or AGAINST it? Vote below!' Share how riding the wave changed your trading. End with: 'Join our VEDD community and learn to catch trends together - comment TREND to join!'",
    suggestedHashtags: ["#TrendTrading", "#VEDDAi", "#VEDDCommunity", "#VoteBelow", "#CommentToJoin"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 5,
    title: "Risk Management - Protect Ya Neck",
    tradingTopic: "Protecting Your Capital",
    tradingLesson: "Real talk - never risk more than 1-2% of your account on one trade. Learn to size your positions based on where your stop loss sits and how big your account is. Keeping your capital safe is priority numero uno. Blow your account and the game is over.",
    scriptureReference: "Proverbs 21:5",
    scriptureText: "The plans of the diligent lead surely to abundance, but everyone who is hasty comes only to poverty.",
    devotionalMessage: "Being diligent means protecting what God blessed you with. Hasty trading without risk management leads to blown accounts. Be a smart steward of your trading bread.",
    contentPrompt: "Create a 'Risk Management Reality Check' post. ASK: 'Be honest - do you risk more than 2% per trade? Comment your % below (no judgment!)' Share the 1-2% rule with real examples. CTA: 'Join our VEDD trading tribe where we keep each other accountable. Link in bio!'",
    suggestedHashtags: ["#RiskManagement", "#VEDDAi", "#TradingTribe", "#BeHonest", "#JoinTheTribe"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 6,
    title: "Stop Loss - Your Trading Insurance",
    tradingTopic: "Setting Protective Stops",
    tradingLesson: "A stop loss is your trading insurance policy. Place stops below support for longs and above resistance for shorts. ATR-based stops are fire because they adapt to how volatile the market is. Protect yourself before you wreck yourself.",
    scriptureReference: "Proverbs 22:3",
    scriptureText: "The prudent sees danger and hides himself, but the simple go on and suffer for it.",
    devotionalMessage: "Smart traders set stop losses to protect themselves from market danger. People who trade without protection get wrecked. Be wise about protecting your capital.",
    contentPrompt: "Share a story about a time a stop loss saved you (or when NOT having one hurt). ASK: 'Have you ever been saved by a stop loss? Tell your story below!' Show how VEDD AI recommends stop levels automatically. CTA: 'Never guess where to put your stop again - try VEDD free!'",
    suggestedHashtags: ["#StopLoss", "#VEDDAi", "#ShareYourStory", "#TradingStories", "#TryVEDDFree"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 7,
    title: "Week 1 Done - Foundation Solid",
    tradingTopic: "Foundation Week Summary",
    tradingLesson: "Review time: Candlesticks, Support/Resistance, Trends, Risk Management, and Stop Losses. These fundamentals are the pillars, fam. You gotta have these locked before moving to the advanced sauce.",
    scriptureReference: "Matthew 7:24-25",
    scriptureText: "Everyone then who hears these words of mine and does them will be like a wise man who built his house on the rock. And the rain fell, and the floods came, and the winds blew and beat on that house, but it did not fall, because it had been founded on the rock.",
    devotionalMessage: "Week 1 was all about building your trading house on rock. When market storms hit - and they will - your foundational knowledge gonna keep you standing strong.",
    contentPrompt: "Celebrate Week 1 with a carousel recap! ASK: 'Which lesson hit hardest for you this week? Comment below!' Share your Week 1 wins and encourage newcomers. CTA: 'Starting Monday, we go deeper - join the VEDD community now so you dont miss Week 2! Comment READY to get started!'",
    suggestedHashtags: ["#Week1Done", "#VEDDAi", "#VEDDCommunity", "#CommentReady", "#StartMonday"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 1,
    category: "review"
  },
  // Week 2: Strategy Development - Building Your Playbook
  {
    dayNumber: 8,
    title: "Moving Averages - Smooth Out The Noise",
    tradingTopic: "Trend Following Indicators",
    tradingLesson: "Moving averages clean up the messy price action so you can see the real trend. 20 EMA shows short-term vibes, 50 EMA medium-term energy, and 200 EMA is the big picture. Learn those MA crossover signals - they hit different.",
    scriptureReference: "Proverbs 4:25-26",
    scriptureText: "Let your eyes look directly forward, and your gaze be straight before you. Ponder the path of your feet; then all your ways will be sure.",
    devotionalMessage: "Moving averages help you look forward clear, cutting through the daily noise. Keep your eyes on the bigger picture while thinking through each trading move.",
    contentPrompt: "Show VEDD AI analyzing moving averages on a real chart. ASK: 'What MA settings do you use? Drop your favorite combo below!' Create a mini-community discussion. CTA: 'Want to see how the pros use MAs? Join our free VEDD community calls - DM me LEARNING!'",
    suggestedHashtags: ["#MovingAverages", "#VEDDAi", "#VEDDCommunity", "#ShareYourSettings", "#DMmeLearning"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 9,
    title: "RSI - Reading Momentum Energy",
    tradingTopic: "Momentum Measurement",
    tradingLesson: "RSI measures momentum on a 0-100 scale. Above 70 means the market might be tired from buying, below 30 means sellers might be exhausted. RSI divergence signals are chef's kiss for catching reversals.",
    scriptureReference: "Galatians 6:9",
    scriptureText: "And let us not grow weary of doing good, for in due season we will reap, if we do not give up.",
    devotionalMessage: "RSI shows us when the market is exhausted - when momentum is stretched too far. In trading and life, gotta know when to rest and when to push, trusting Gods timing for the harvest.",
    contentPrompt: "Post a VEDD AI analysis showing RSI divergence in action. ASK: 'Have you ever caught a reversal using RSI? Share your win below!' Build community through shared stories. CTA: 'VEDD AI spots RSI signals automatically - try it free and join 1000+ traders in our community!'",
    suggestedHashtags: ["#RSI", "#VEDDAi", "#ShareYourWin", "#VEDDCommunity", "#TryItFree"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 10,
    title: "MACD - The Trend Momentum Combo",
    tradingTopic: "Trend Momentum Indicator",
    tradingLesson: "MACD shows the relationship between two moving averages. When MACD line crosses above signal line, bulls taking over. When that histogram grows, momentum is picking up steam. Master these signals and you cooking.",
    scriptureReference: "Amos 3:3",
    scriptureText: "Do two walk together, unless they have agreed to meet?",
    devotionalMessage: "MACD shows when price and momentum walking together in agreement. In trading and life, alignment creates power. Trade when signals agree, step back when they beefing.",
    contentPrompt: "Create a 'MACD Made Simple' post with VEDD AI showing real crossover signals. ASK: 'MACD lovers, what other indicator do you pair it with? Comment below!' Build engagement. CTA: 'Stop missing crossovers - VEDD alerts you automatically. Comment ALERTS to learn more!'",
    suggestedHashtags: ["#MACD", "#VEDDAi", "#CommentAlerts", "#VEDDCommunity", "#SimplifiedTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 11,
    title: "Multi-Timeframe - See The Full Picture",
    tradingTopic: "Timeframe Confluence",
    tradingLesson: "Analyze from bigger to smaller timeframes. Daily chart shows the trend, 4H shows structure, 1H shows where to enter. When all timeframes saying the same thing, your confidence gonna be through the roof.",
    scriptureReference: "Proverbs 11:14",
    scriptureText: "Where there is no guidance, a people falls, but in an abundance of counselors there is safety.",
    devotionalMessage: "Multiple timeframes are like counselors, each giving different perspective. Safety comes from gathering input from multiple sources before pulling the trigger.",
    contentPrompt: "Show VEDDs multi-timeframe EA analysis feature in action. ASK: 'What timeframes do YOU stack? Comment your combo!' Encourage knowledge sharing. CTA: 'Our VEDD tribe analyzes charts together every week - join our next live session! Comment LIVE to get invited!'",
    suggestedHashtags: ["#MultiTimeframe", "#VEDDAi", "#CommentLive", "#VEDDTribe", "#WeeklySession"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 12,
    title: "Entry Game - Timing Is Everything",
    tradingTopic: "Timing Your Entry",
    tradingLesson: "The best entries stack multiple confirmations: trend direction, support/resistance levels, indicator signals, and candlestick patterns all lining up. Patience for the A+ setup is key - stop forcing trades that aint there.",
    scriptureReference: "Habakkuk 2:3",
    scriptureText: "For still the vision awaits its appointed time; it hastens to the end—it will not lie. If it seems slow, wait for it; it will surely come; it will not delay.",
    devotionalMessage: "Wait for your trading setup like waiting for a vision to come through. The best entries come to those who patient for everything to line up. Rushing in leads to L's.",
    contentPrompt: "Post a 'Perfect Entry Checklist' carousel. ASK: 'How many confirmations do you wait for before entering? Drop your number below!' Drive comments. CTA: 'VEDD AI checks multiple confirmations for you - never second-guess an entry again. Start free today!'",
    suggestedHashtags: ["#TradeEntry", "#VEDDAi", "#DropYourNumber", "#PerfectEntry", "#StartFreeToday"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 13,
    title: "Take Profit - Know When To Cash Out",
    tradingTopic: "Exit Strategy Planning",
    tradingLesson: "Plan your exits before you even get in. Use previous highs/lows, Fibonacci extensions, and risk-reward ratios to set them take profit targets. Taking partial profits along the way can lock in gains while letting winners run.",
    scriptureReference: "Luke 14:28",
    scriptureText: "For which of you, desiring to build a tower, does not first sit down and count the cost, whether he has enough to complete it?",
    devotionalMessage: "Counting the cost includes knowing when youre out. Plan your take profits before entering, just like a builder plans before breaking ground.",
    contentPrompt: "Create a 'Take Profit Strategies' post with real examples from VEDD analysis. ASK: 'Do you take partial profits or let it ride? Vote in comments!' Drive engagement. CTA: 'Join our VEDD community and share strategies with 1000+ traders. Comment JOIN to get access!'",
    suggestedHashtags: ["#TakeProfit", "#VEDDAi", "#VoteInComments", "#CommentJoin", "#VEDDCommunity"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 14,
    title: "Week 2 Complete - Strategy Unlocked",
    tradingTopic: "Strategy Week Summary",
    tradingLesson: "Review: Moving Averages, RSI, MACD, Multi-Timeframe Analysis, Entry Strategies, and Take Profit Planning. You now got the tools to build a complete trading strategy. Thats a W.",
    scriptureReference: "James 1:4",
    scriptureText: "And let steadfastness have its full effect, that you may be perfect and complete, lacking in nothing.",
    devotionalMessage: "Week 2 added powerful tools to your arsenal. Let that consistency in learning have its full effect. Youre becoming more complete as a trader every day.",
    contentPrompt: "Week 2 celebration post! ASK: 'Which indicator became your new favorite this week? Comment below!' Share your strategy development journey. CTA: 'Week 3 is about MINDSET - the real game changer. DM me NOW to join before Monday!'",
    suggestedHashtags: ["#Week2Done", "#VEDDAi", "#NewFavorite", "#DMmeNow", "#Week3Monday"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 2,
    category: "review"
  },
  // Week 3: Trading Mindset - Master Your Mental
  {
    dayNumber: 15,
    title: "Trading Psychology - Control Your Mind",
    tradingTopic: "Mastering Your Mind",
    tradingLesson: "Your biggest enemy in trading is yourself. Fear makes you exit too early, greed makes you stay too long. Develop emotional discipline through journaling and self-awareness. The mind game is everything.",
    scriptureReference: "2 Timothy 1:7",
    scriptureText: "For God gave us a spirit not of fear but of power and love and self-control.",
    devotionalMessage: "God didnt give us fear - He gave us power and self-control. Apply that same energy to trading. Master your emotions and youll master the markets.",
    contentPrompt: "Create a 'Trading Psychology Check' post. ASK: 'Whats your biggest mental challenge - FEAR or GREED? Vote below!' Share personal struggles and wins. CTA: 'Our VEDD community holds each other accountable on mindset. Join us - comment MINDSET to connect!'",
    suggestedHashtags: ["#TradingPsychology", "#VEDDAi", "#VoteBelow", "#CommentMindset", "#VEDDCommunity"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 16,
    title: "Patience Pays - Wait For Your Setup",
    tradingTopic: "Developing Patience",
    tradingLesson: "The best traders are the most patient. Waiting for A+ setups means less trades but higher win rate. Quality over quantity every time. Let the trade come to you.",
    scriptureReference: "Psalm 37:7",
    scriptureText: "Be still before the Lord and wait patiently for him; fret not yourself over the one who prospers in his way.",
    devotionalMessage: "Being still and patient is hard when you see others winning. But your setups are different than theirs. Trust your process and wait for your moments.",
    contentPrompt: "Post about patience with a VEDD analysis showing an A+ setup you waited for. ASK: 'How long do you wait for a setup - minutes, hours, or days? Comment below!' CTA: 'VEDD AI alerts you when setups form so you dont have to stare at charts. Try it free - link in bio!'",
    suggestedHashtags: ["#TradingPatience", "#VEDDAi", "#CommentBelow", "#FreeAlerts", "#VEDDCommunity"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 17,
    title: "Handling Losses - They Part Of The Game",
    tradingTopic: "Loss Management",
    tradingLesson: "Every trader takes Ls - its part of the game. What separates winners is how they respond. Take the loss, learn the lesson, move on. Dont revenge trade, dont tilt, dont let one loss turn into five.",
    scriptureReference: "Proverbs 24:16",
    scriptureText: "For the righteous falls seven times and rises again, but the wicked stumble in times of calamity.",
    devotionalMessage: "Falling isnt failing - staying down is. When you take a trading loss, rise again with new wisdom. Each loss is a lesson if youre paying attention.",
    contentPrompt: "Create a vulnerable 'My Biggest Loss & What I Learned' post. ASK: 'Whats your worst trading loss? Share below - no judgment, just learning!' Build community through shared struggle. CTA: 'Our VEDD tribe supports each other through the Ls. Join a community that gets it - DM me SUPPORT!'",
    suggestedHashtags: ["#TradingLosses", "#VEDDAi", "#ShareNoJudgment", "#DMmeSupport", "#VEDDTribe"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 18,
    title: "FOMO Is The Enemy - Stay In Your Lane",
    tradingTopic: "Avoiding FOMO Trading",
    tradingLesson: "FOMO (Fear Of Missing Out) will wreck your account faster than anything. Seeing a move you missed and jumping in late is how you get burned. There will always be another trade. Stay disciplined.",
    scriptureReference: "Proverbs 14:29",
    scriptureText: "Whoever is slow to anger has great understanding, but he who has a hasty temper exalts folly.",
    devotionalMessage: "Being slow to react and quick to think shows understanding. Hasty entries driven by FOMO is straight folly. Stay in your lane and trade your plan.",
    contentPrompt: "Share a 'FOMO Confession' story - a time you chased and got burned. ASK: 'Have you ever FOMO'd into a trade and regretted it? Tell your story below!' Build connection. CTA: 'Our VEDD community keeps each other in check. Before you FOMO, post in our group first! Comment DISCIPLINE to join!'",
    suggestedHashtags: ["#NoFOMO", "#VEDDAi", "#TellYourStory", "#CommentDiscipline", "#VEDDCommunity"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 19,
    title: "Trading Journal - Track Your Moves",
    tradingTopic: "Journaling Your Trades",
    tradingLesson: "A trading journal is your personal playbook for improvement. Record every trade: entry, exit, why you took it, how you felt. Review weekly to spot patterns in your wins and losses.",
    scriptureReference: "Lamentations 3:40",
    scriptureText: "Let us test and examine our ways, and return to the Lord!",
    devotionalMessage: "Self-examination leads to growth. Testing and examining your trading ways through journaling reveals patterns you cant see otherwise. Reflection is key to improvement.",
    contentPrompt: "Show your trading journal setup (or VEDD analysis history). ASK: 'Do you journal your trades? If yes, whats the #1 thing you track? Comment below!' CTA: 'VEDD AI saves all your analyses automatically - your journal is built-in! Start tracking your growth today - link in bio!'",
    suggestedHashtags: ["#TradingJournal", "#VEDDAi", "#CommentBelow", "#AutomaticJournal", "#StartToday"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 20,
    title: "Consistency Over Everything",
    tradingTopic: "Building Consistent Habits",
    tradingLesson: "Consistency beats intensity every time. Trading the same strategy, same risk, same routine daily builds the discipline needed for long-term success. One fire week means nothing if you cant sustain it.",
    scriptureReference: "1 Corinthians 9:27",
    scriptureText: "But I discipline my body and keep it under control, lest after preaching to others I myself should be disqualified.",
    devotionalMessage: "Discipline your trading like an athlete disciplines their body. Keep yourself under control daily. Consistency is what separates pros from amateurs.",
    contentPrompt: "Post your 'Daily Trading Routine' with times and activities. ASK: 'What does YOUR trading day look like? Share your routine below!' Inspire others to create structure. CTA: 'Join our VEDD morning analysis calls and build a consistent routine with the tribe. Comment ROUTINE to get the schedule!'",
    suggestedHashtags: ["#Consistency", "#VEDDAi", "#ShareYourRoutine", "#CommentRoutine", "#VEDDMorningCall"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 21,
    title: "Week 3 Complete - Mindset On Point",
    tradingTopic: "Mindset Week Summary",
    tradingLesson: "Review: Psychology, Patience, Loss Management, FOMO Avoidance, Journaling, and Consistency. Your mind is now as sharp as your strategy. Thats the complete package.",
    scriptureReference: "Romans 12:2",
    scriptureText: "Do not be conformed to this world, but be transformed by the renewal of your mind.",
    devotionalMessage: "Week 3 was all about renewing your trading mind. Dont conform to amateur habits - transform through wisdom and discipline. Your mindset is renewed.",
    contentPrompt: "Week 3 mindset transformation post! ASK: 'What was your biggest mindset breakthrough this week? Drop it below!' Celebrate community progress. CTA: 'Week 4 is EXECUTION - where we put it all together. Dont miss it! Comment EXECUTE to stay in the loop!'",
    suggestedHashtags: ["#Week3Done", "#VEDDAi", "#MindsetBreakthrough", "#CommentExecute", "#Week4Coming"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 3,
    category: "review"
  },
  // Week 4: Trade Execution - Time To Execute
  {
    dayNumber: 22,
    title: "Pre-Trade Checklist - Run The Checks",
    tradingTopic: "Trade Preparation",
    tradingLesson: "Before every trade, run your checklist: Is the trend confirmed? Are you at a key level? Do indicators agree? Is risk calculated? Never skip the checklist - it saves you from emotional trades.",
    scriptureReference: "Proverbs 16:3",
    scriptureText: "Commit your work to the Lord, and your plans will be established.",
    devotionalMessage: "Commit your trading to the Lord and establish your plans through proper preparation. A pre-trade checklist is your plan in action.",
    contentPrompt: "Create a shareable 'Pre-Trade Checklist' graphic your audience can save. ASK: 'Whats on YOUR pre-trade checklist that I might be missing? Add yours below!' Crowdsource wisdom. CTA: 'VEDD AI runs this checklist automatically on every chart. Try it free and never skip a step!'",
    suggestedHashtags: ["#PreTradeChecklist", "#VEDDAi", "#SaveThis", "#AddYours", "#TryItFree"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 23,
    title: "Order Types - Know Your Options",
    tradingTopic: "Understanding Order Types",
    tradingLesson: "Market orders fill instant but you get whatever price. Limit orders let you set your price but might not fill. Stop orders trigger when price hits your level. Know when to use each.",
    scriptureReference: "Proverbs 21:29",
    scriptureText: "A wicked man puts on a bold face, but the upright gives thought to his ways.",
    devotionalMessage: "Give thought to how you enter trades. Understanding order types means you control your entries instead of just market buying blindly.",
    contentPrompt: "Create an 'Order Types Explained' carousel. ASK: 'Team Limit Orders or Team Market Orders? Vote in the comments!' Create friendly debate. CTA: 'Our VEDD community debates trading tactics every week - join the conversation! Comment DEBATE to get access!'",
    suggestedHashtags: ["#OrderTypes", "#VEDDAi", "#TeamLimit", "#TeamMarket", "#CommentDebate"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 24,
    title: "Position Sizing - Right Size Your Trades",
    tradingTopic: "Calculating Position Size",
    tradingLesson: "Position sizing is how you control risk on every trade. Formula: Risk Amount / Stop Loss Distance = Position Size. Never eyeball it - calculate it every time. This is how pros protect capital.",
    scriptureReference: "Luke 16:10",
    scriptureText: "One who is faithful in a very little is also faithful in much, and one who is dishonest in a very little is also dishonest in much.",
    devotionalMessage: "Be faithful in sizing your trades correctly, even on small accounts. Master position sizing now and itll serve you when your account grows.",
    contentPrompt: "Post a 'Position Sizing Calculator' walkthrough with real numbers. ASK: 'Drop your account size below (even if its small!) and Ill show you proper lot sizing!' Offer personalized help. CTA: 'Want a position size calculator built-in? VEDD does the math for you. Start free!'",
    suggestedHashtags: ["#PositionSizing", "#VEDDAi", "#DropYourSize", "#FreeMath", "#StartFree"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 25,
    title: "Trade Management - Active Management",
    tradingTopic: "Managing Open Positions",
    tradingLesson: "Once youre in a trade, the job isnt done. Know when to move stop loss to breakeven, when to take partial profits, when to let it ride. Active management turns good trades into great trades.",
    scriptureReference: "Proverbs 27:23",
    scriptureText: "Know well the condition of your flocks, and give attention to your herds.",
    devotionalMessage: "Know the condition of your open trades like a shepherd knows their flock. Give attention to whats happening and manage actively.",
    contentPrompt: "Post a 'Trade Management Decision Tree' people can screenshot and save. ASK: 'When do YOU move to breakeven - at 1R, 1.5R, or never? Comment your rule!' Share tactics. CTA: 'Join our VEDD live trading room where we manage trades together in real-time. Comment LIVEROOM!'",
    suggestedHashtags: ["#TradeManagement", "#VEDDAi", "#ScreenshotThis", "#CommentLiveRoom", "#LiveTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 26,
    title: "Scaling In & Out - Layer Your Trades",
    tradingTopic: "Scaling Strategies",
    tradingLesson: "Scaling in means adding to a winning position at better prices. Scaling out means taking partial profits as price moves your way. Both strategies reduce risk and lock in gains.",
    scriptureReference: "Ecclesiastes 11:2",
    scriptureText: "Give a portion to seven, or even to eight, for you know not what disaster may happen on earth.",
    devotionalMessage: "Diversify your entries and exits across multiple levels. You dont know what the market will do, so spread your risk wisely.",
    contentPrompt: "Create a 'Scaling Strategies' guide with examples from your own trades. ASK: 'Do you scale in, scale out, or go all-in? Comment your style!' Encourage sharing. CTA: 'Tag a trading friend who needs to learn about scaling - help them level up!'",
    suggestedHashtags: ["#ScalingIn", "#VEDDAi", "#CommentYourStyle", "#TagAFriend", "#LevelUp"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 27,
    title: "News Trading - Handle The Volatility",
    tradingTopic: "Trading Around News Events",
    tradingLesson: "News events create crazy volatility. Know the economic calendar, widen stops or stay flat during major announcements. FOMC, NFP, CPI - these events move markets hard. Respect the risk.",
    scriptureReference: "Proverbs 22:7",
    scriptureText: "The prudent sees danger and hides himself, but the simple go on and suffer for it.",
    devotionalMessage: "Prudent traders see news events coming and protect themselves. The simple ignore the calendar and get stopped out by volatility spikes.",
    contentPrompt: "Post a 'News Trading Survival Guide' with this weeks big events. ASK: 'Are you trading news this week or sitting out? Comment your plan!' Build anticipation. CTA: 'Our VEDD tribe shares news alerts and prep together - join us before the next FOMC! Comment FOMC!'",
    suggestedHashtags: ["#NewsTrading", "#VEDDAi", "#CommentYourPlan", "#CommentFOMC", "#VEDDTribe"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 28,
    title: "Week 4 Complete - Execution Mode",
    tradingTopic: "Execution Week Summary",
    tradingLesson: "Review: Checklists, Order Types, Position Sizing, Trade Management, Scaling, and News Trading. You now know how to execute trades like a pro. Knowledge is power - go use it.",
    scriptureReference: "James 1:22",
    scriptureText: "But be doers of the word, and not hearers only, deceiving yourselves.",
    devotionalMessage: "Dont just hear this teaching - do it. Apply what youve learned about execution. Knowledge without action is useless.",
    contentPrompt: "Week 4 execution celebration! ASK: 'Show your best trade from this week! Post your chart in the comments!' Create a mini showcase. CTA: 'Week 5 is ADVANCED mode - the sauce that separates amateurs from pros. Comment ADVANCED to lock in your spot!'",
    suggestedHashtags: ["#Week4Done", "#VEDDAi", "#ShowYourTrade", "#CommentAdvanced", "#ProLevel"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 4,
    category: "review"
  },
  // Week 5: Advanced Concepts - Level Up
  {
    dayNumber: 29,
    title: "Fibonacci Levels - The Golden Ratio",
    tradingTopic: "Fibonacci Retracements",
    tradingLesson: "Fibonacci levels are based on the golden ratio found everywhere in nature. The 38.2%, 50%, and 61.8% retracement levels are where price often bounces. These levels are spooky accurate.",
    scriptureReference: "Psalm 19:1",
    scriptureText: "The heavens declare the glory of God, and the sky above proclaims his handiwork.",
    devotionalMessage: "Gods mathematical patterns appear in the heavens, in nature, and yes, in the markets. Fibonacci levels reflect divine order in chaos.",
    contentPrompt: "Post Fibonacci levels drawn by VEDD AI on a real chart. ASK: 'What Fib level do you respect most - 38.2%, 50%, or 61.8%? Vote below!' Create discussion. CTA: 'VEDD AI draws Fibs automatically - stop doing math manually. Try it free and join our Fib-loving tribe!'",
    suggestedHashtags: ["#Fibonacci", "#VEDDAi", "#VoteBelow", "#AutoFibs", "#VEDDTribe"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 30,
    title: "Supply & Demand Zones - Where Big Money Plays",
    tradingTopic: "Institutional Order Flow",
    tradingLesson: "Supply and demand zones show where big money placed orders. Price often returns to these areas before continuing. Theyre like support/resistance but more precise. Learn to spot them.",
    scriptureReference: "Proverbs 13:22",
    scriptureText: "A good man leaves an inheritance to his children's children, but the sinner's wealth is laid up for the righteous.",
    devotionalMessage: "Institutions leave footprints in the charts through supply and demand zones. Learn to read where big money is positioned.",
    contentPrompt: "Show VEDD AI identifying supply/demand zones on a chart. ASK: 'Can you spot where the big money is positioned on YOUR charts? Share your zone below!' Encourage chart sharing. CTA: 'Want to trade like institutions? Our VEDD community studies order flow together. Comment ORDERFLOW to join!'",
    suggestedHashtags: ["#SupplyDemand", "#VEDDAi", "#ShareYourZone", "#CommentOrderFlow", "#VEDDCommunity"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 31,
    title: "Volume Analysis - Follow The Money",
    tradingTopic: "Reading Volume",
    tradingLesson: "Volume confirms price moves. High volume on a breakout means its real. Low volume on a move means it might reverse. Volume is like truth serum for price action.",
    scriptureReference: "Matthew 6:21",
    scriptureText: "For where your treasure is, there your heart will be also.",
    devotionalMessage: "Volume shows where traders put their money - their treasure. High volume reveals commitment. Low volume reveals hesitation. Follow the money.",
    contentPrompt: "Create a 'Volume Tells The Truth' post with real volume analysis examples. ASK: 'Do you use volume in your trading? Comment YES or NOT YET!' Gauge your audience. CTA: 'VEDD AI includes volume analysis in every chart review. See it in action - try free today!'",
    suggestedHashtags: ["#VolumeAnalysis", "#VEDDAi", "#CommentYesOrNo", "#VolumeTruth", "#TryFreeToday"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 32,
    title: "Chart Patterns - The Classics",
    tradingTopic: "Pattern Recognition",
    tradingLesson: "Head and shoulders, double tops/bottoms, triangles, flags - these patterns repeat because human psychology repeats. Learn the classics and youll see setups everywhere.",
    scriptureReference: "Ecclesiastes 1:9",
    scriptureText: "What has been is what will be, and what has been done is what will be done, and there is nothing new under the sun.",
    devotionalMessage: "Nothing new under the sun - including chart patterns. Human behavior creates the same patterns generation after generation. History rhymes.",
    contentPrompt: "Create a 'Pattern Spotlight' carousel showing head & shoulders, double top, triangles. ASK: 'Which pattern has made you the most money? Comment below!' Share wins. CTA: 'VEDD AI spots these patterns instantly. Upload any chart and see what AI finds - its free to start!'",
    suggestedHashtags: ["#ChartPatterns", "#VEDDAi", "#PatternWins", "#CommentBelow", "#FreeToStart"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 33,
    title: "Divergence Trading - Hidden Signals",
    tradingTopic: "RSI & MACD Divergence",
    tradingLesson: "Divergence happens when price makes new highs but indicators dont confirm. Its a warning sign of potential reversal. Hidden divergence signals trend continuation. Both are powerful.",
    scriptureReference: "Proverbs 20:12",
    scriptureText: "The hearing ear and the seeing eye, the Lord has made them both.",
    devotionalMessage: "God gave us eyes to see what others miss. Divergence is a hidden signal that most traders dont catch. Train your eyes to see the invisible.",
    contentPrompt: "Post a 'Divergence Masterclass' with VEDD AI highlighting divergence on charts. ASK: 'Have you ever caught a divergence reversal? Share your story!' Collect testimonials. CTA: 'Our advanced VEDD traders spot divergence together. Ready to level up? Comment DIVERGENCE!'",
    suggestedHashtags: ["#Divergence", "#VEDDAi", "#ShareYourStory", "#CommentDivergence", "#LevelUp"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 34,
    title: "Market Structure - Reading The Blueprint",
    tradingTopic: "Understanding Market Structure",
    tradingLesson: "Market structure is the blueprint of price movement. Higher highs and higher lows in uptrend. Lower highs and lower lows in downtrend. Break of structure signals a change. Read the blueprint.",
    scriptureReference: "1 Corinthians 14:40",
    scriptureText: "But all things should be done decently and in order.",
    devotionalMessage: "Markets have order and structure, even when they look chaotic. Learn to read that order and trade with the structure, not against it.",
    contentPrompt: "Create a 'Market Structure Breakdown' video or carousel. ASK: 'How do you identify break of structure? Share your method below!' Learn from each other. CTA: 'VEDD AI reads market structure automatically - never miss a BOS again. Join the tribe - comment STRUCTURE!'",
    suggestedHashtags: ["#MarketStructure", "#VEDDAi", "#ShareYourMethod", "#CommentStructure", "#BOSTrading"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 35,
    title: "Week 5 Complete - Advanced Mode Unlocked",
    tradingTopic: "Advanced Concepts Summary",
    tradingLesson: "Review: Fibonacci, Supply/Demand, Volume, Chart Patterns, Divergence, and Market Structure. You now have advanced tools most traders never learn. Use them wisely.",
    scriptureReference: "Proverbs 24:5",
    scriptureText: "A wise man is full of strength, and a man of knowledge enhances his might.",
    devotionalMessage: "Week 5 filled you with advanced knowledge that enhances your trading strength. Wisdom and knowledge together create power. Youre leveling up.",
    contentPrompt: "Week 5 advanced graduation post! ASK: 'Which advanced concept blew your mind this week? Comment below!' Celebrate the journey. CTA: 'Week 6 is about BUILDING YOUR COMMUNITY and monetizing your skills. The real money starts now! Comment WEEK6 to continue!'",
    suggestedHashtags: ["#Week5Done", "#VEDDAi", "#MindBlown", "#CommentWeek6", "#BuildYourTribe"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 5,
    category: "review"
  },
  // Week 6: Building Your Business - Ambassador Life
  {
    dayNumber: 36,
    title: "Creating Trading Content - Share Your Journey",
    tradingTopic: "Content Creation Basics",
    tradingLesson: "Your trading journey is content gold. Share your analyses, your wins, your lessons. Authenticity beats perfection. Start creating and posting consistently.",
    scriptureReference: "Matthew 5:14-15",
    scriptureText: "You are the light of the world. A city set on a hill cannot be hidden. Nor do people light a lamp and put it under a basket.",
    devotionalMessage: "Dont hide your trading knowledge - share it. Your light can guide others on their journey. Be the city on the hill for aspiring traders.",
    contentPrompt: "Post your first (or favorite) piece of trading content you created. ASK: 'What stops YOU from posting trading content? Comment your biggest blocker!' Address fears. CTA: 'Start creating with the VEDD community - we support each others content. DM me CONTENT to join our creator group!'",
    suggestedHashtags: ["#ContentCreation", "#VEDDAi", "#CommentYourBlocker", "#DMmeContent", "#CreatorCommunity"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 6,
    category: "execution"
  },
  {
    dayNumber: 37,
    title: "Building Your VEDD Tribe - Community First",
    tradingTopic: "Community Building",
    tradingLesson: "VEDD is an Online University-style community experience, not just a trading tool. Your role is to build a supportive tribe where traders learn together, hold each other accountable, and celebrate wins as a family. Start with quality over quantity - 10 committed members beats 100 passive ones.",
    scriptureReference: "Proverbs 11:25",
    scriptureText: "Whoever brings blessing will be enriched, and one who waters will himself be watered.",
    devotionalMessage: "Bless your community with knowledge and support, and youll be blessed in return. Water others with value and watch your tribe flourish. Community building is an investment that compounds.",
    contentPrompt: "Share your 'Why I Build Community' story. ASK: 'What does trading community mean to YOU? Comment your definition!' Create connection. CTA: 'Start building YOUR VEDD tribe today. DM me TRIBE and Ill send you the community starter kit!'",
    suggestedHashtags: ["#VEDDCommunity", "#TradingTribe", "#DMmeTribe", "#StarterKit", "#BuildWithUs"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 6,
    category: "execution"
  },
  {
    dayNumber: 38,
    title: "Hosting Your First VEDD Community Event",
    tradingTopic: "Event Hosting",
    tradingLesson: "Use VEDDs Host Dashboard to create live events for your community. Start with a simple Chart Review session - walk through AI analysis of a chart, answer questions, and show the platform in action. Record everything so people who missed it can catch the replay.",
    scriptureReference: "Hebrews 10:24-25",
    scriptureText: "And let us consider how to stir up one another to love and good works, not neglecting to meet together.",
    devotionalMessage: "Live community events are modern gatherings where we encourage and teach each other. Dont neglect bringing your tribe together - both online and in real time.",
    contentPrompt: "Create an event announcement post! ASK: 'What trading topic should I cover in my next live session? Vote below!' Let your audience choose. CTA: 'Register for my VEDD community event NOW - spots are limited! Comment REGISTER to save your seat!'",
    suggestedHashtags: ["#VEDDLive", "#VoteBelow", "#CommentRegister", "#LiveEvent", "#LimitedSpots"],
    mediaType: "video",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 6,
    category: "execution"
  },
  {
    dayNumber: 39,
    title: "Member Spotlights - Celebrate Your Tribe",
    tradingTopic: "Community Recognition",
    tradingLesson: "Recognize and celebrate your community members! Spotlight traders who hit milestones - first chart analysis, first EA created, 30-day streak. Share their success stories with permission. When you celebrate others, they become your biggest advocates.",
    scriptureReference: "Romans 12:15",
    scriptureText: "Rejoice with those who rejoice, weep with those who weep.",
    devotionalMessage: "True community means celebrating each others wins and supporting through losses. When your tribe member hits a milestone, make it a big deal. Their success is your success.",
    contentPrompt: "Create a '(Member Name) Spotlight' celebrating someone in your community. ASK: 'Want to be featured next? Comment your biggest trading win below and you might be next!' Encourage participation. CTA: 'Join the VEDD community where wins get celebrated! Link in bio!'",
    suggestedHashtags: ["#MemberSpotlight", "#CommentYourWin", "#VEDDAi", "#GetFeatured", "#JoinNow"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 6,
    category: "execution"
  },
  {
    dayNumber: 40,
    title: "Accountability Partners - Trading Buddies",
    tradingTopic: "Peer Accountability",
    tradingLesson: "Help community members find accountability partners - trading buddies who check in on each others discipline. Set up simple check-ins: Did you follow your risk rules? Did you journal your trades? Did you stick to your strategy? This buddy system keeps traders on track.",
    scriptureReference: "Ecclesiastes 4:9-10",
    scriptureText: "Two are better than one, because they have a good reward for their toil. For if they fall, one will lift up his fellow.",
    devotionalMessage: "Two traders are better than one. When you fall into bad habits, your accountability partner lifts you up. Build this into your community culture.",
    contentPrompt: "Create a 'Find Your Trading Buddy' post. ASK: 'Looking for an accountability partner? Comment PARTNER and your timezone - lets match you up!' Facilitate connections. CTA: 'The VEDD community matches trading buddies who keep each other on track. Join the matchmaking!'",
    suggestedHashtags: ["#TradingBuddy", "#CommentPartner", "#VEDDAi", "#Matchmaking", "#AccountabilityWorks"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 6,
    category: "execution"
  },
  {
    dayNumber: 41,
    title: "Welcoming New Members - First Impressions",
    tradingTopic: "Member Onboarding",
    tradingLesson: "First impressions make or break retention. Send every new member a personal welcome message within 24 hours. Ask about their trading experience and goals. Guide them to their first chart analysis. Make them feel like they just joined a family, not signed up for software.",
    scriptureReference: "Romans 15:7",
    scriptureText: "Therefore welcome one another as Christ has welcomed you, for the glory of God.",
    devotionalMessage: "Welcome new members the way you would want to be welcomed. Personal attention creates belonging. That 5-minute welcome message can create a lifelong community member.",
    contentPrompt: "Create a 'Welcome To The VEDD Family' template post. ASK: 'New here? Drop a wave emoji below and introduce yourself! Where are you from and what do you trade?' Build instant connection. CTA: 'Not in the family yet? Join now - link in bio - and Ill personally welcome you!'",
    suggestedHashtags: ["#WelcomeFamily", "#IntroduceYourself", "#VEDDAi", "#WaveEmoji", "#JoinNow"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 6,
    category: "execution"
  },
  {
    dayNumber: 42,
    title: "Week 6 Complete - Community Builder",
    tradingTopic: "Community Building Summary",
    tradingLesson: "Review: Building your VEDD tribe, hosting community events, member spotlights, accountability partners, and welcoming new members. Youre now equipped to build and nurture a thriving trading community around the VEDD Online University experience.",
    scriptureReference: "2 Timothy 2:2",
    scriptureText: "And what you have heard from me in the presence of many witnesses entrust to faithful men, who will be able to teach others also.",
    devotionalMessage: "What youve learned about community building, now pass on to others. Train faithful community members who will continue growing and nurturing the tribe. Thats the VEDD ambassador mission.",
    contentPrompt: "Week 6 Community Builder celebration! ASK: 'How many people are in your trading tribe right now? Drop your number below - even if its just 1!' Normalize small starts. CTA: 'Final Week 7 is graduation! Comment GRADUATION to finish strong with us!'",
    suggestedHashtags: ["#Week6Done", "#DropYourNumber", "#CommentGraduation", "#VEDDAi", "#FinishStrong"],
    mediaType: "carousel",
    tokenReward: 25,
    bonusTokens: 15,
    weekNumber: 6,
    category: "review"
  },
  // Final Days: Certification & Celebration
  {
    dayNumber: 43,
    title: "Final Review - Everything Youve Learned",
    tradingTopic: "Complete Program Review",
    tradingLesson: "Review all 6 weeks: Foundation, Strategy, Mindset, Execution, Advanced Concepts, and Ambassador Business. You have a complete trading education and the tools to share it.",
    scriptureReference: "Philippians 3:14",
    scriptureText: "I press on toward the goal for the prize of the upward call of God in Christ Jesus.",
    devotionalMessage: "Youve pressed on through 43 days of training. The goal is in sight. Keep pressing toward the prize of being a certified ambassador.",
    contentPrompt: "Create a 'My 44-Day Journey' recap carousel or video. ASK: 'What would you do with 44 days of focused trading education? Comment your goal!' Inspire action. CTA: 'Ready to start YOUR 44-day journey? Comment START and Ill send you Day 1!'",
    suggestedHashtags: ["#44DayJourney", "#CommentYourGoal", "#CommentStart", "#VEDDAi", "#YourJourneyBegins"],
    mediaType: "carousel",
    tokenReward: 25,
    bonusTokens: 15,
    weekNumber: 7,
    category: "review"
  },
  {
    dayNumber: 44,
    title: "Graduation Day - Youre Certified!",
    tradingTopic: "Ambassador Certification",
    tradingLesson: "Congratulations! You completed the 44-day Ambassador Training Program. Youre now a Certified VEDD AI Ambassador with the knowledge, skills, and authority to represent the platform.",
    scriptureReference: "2 Timothy 4:7-8",
    scriptureText: "I have fought the good fight, I have finished the race, I have kept the faith. Henceforth there is laid up for me the crown of righteousness.",
    devotionalMessage: "You fought the good fight of learning, you finished the 44-day race, you kept faith in the process. Your crown awaits - wear your certification with honor.",
    contentPrompt: "GRADUATION POST! Share your official VEDD Ambassador certificate. ASK: 'Whos ready to join the next cohort? Comment NEXT COHORT to reserve your spot!' Create urgency. CTA: 'Limited spots for the next 44-day journey. Starts Monday - DM me NOW to enroll!'",
    suggestedHashtags: ["#Graduation", "#CertifiedAmbassador", "#NextCohort", "#VEDDAi", "#DMmeNow"],
    mediaType: "video",
    tokenReward: 50,
    bonusTokens: 50,
    weekNumber: 7,
    category: "review"
  }
];

export default { ambassadorContentCurriculum };
