export interface DailyLessonData {
  dayNumber: number;
  title: string;
  tradingTopic: string;
  tradingLesson: string;
  scriptureReference: string;
  scriptureText: string;
  devotionalMessage: string;
  contentPrompt: string;
  suggestedHashtags: string[];
  mediaType: 'image' | 'video' | 'carousel';
  tokenReward: number;
  bonusTokens: number;
  weekNumber: number;
  category: 'foundation' | 'strategy' | 'mindset' | 'execution' | 'review';
}

export const ambassadorContentCurriculum: DailyLessonData[] = [
  // Week 1: Foundation - Lets Get This Bread
  {
    dayNumber: 1,
    title: "Yo, Your Trading Journey Starts Now",
    tradingTopic: "Introduction to Chart Analysis",
    tradingLesson: "Every trader who made it big started right here - learning to read charts. Today we breaking down candlestick patterns, the building blocks that show you what the market is really doing. No cap, this is where your bag starts.",
    scriptureReference: "Proverbs 24:27",
    scriptureText: "Prepare your work outside; get everything ready for yourself in the field, and after that build your house.",
    devotionalMessage: "Scripture says prep before you build, fam. Same energy in trading - you gotta lay that foundation first. Master the basics and everything else falls into place.",
    contentPrompt: "Drop an inspiring post about starting your trading journey the right way. Talk about why learning chart basics before throwing money at trades is the move. Add that faith-based message about building on solid ground.",
    suggestedHashtags: ["#TradingJourney", "#ChartGame", "#FaithAndFinance", "#VEDDAi", "#LetsGetIt"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 2,
    title: "Candlesticks - Reading The Story",
    tradingTopic: "Candlestick Patterns Basics",
    tradingLesson: "Candlesticks be telling stories of bulls and bears throwing hands in the market. Today you learning bullish engulfing, bearish engulfing, and doji patterns - these three right here show you when the market is about to flip or when its straight confused.",
    scriptureReference: "Ecclesiastes 3:1",
    scriptureText: "For everything there is a season, and a time for every matter under heaven.",
    devotionalMessage: "Markets got seasons too - times to buy, times to sell, times to chill. Wisdom is knowing what season youre in. Let these candlestick patterns show you the markets current mood.",
    contentPrompt: "Put the squad on about candlestick patterns and what they really mean. Connect it to that seasons concept - knowing when to move and when to wait. Encourage your people to level up their pattern game.",
    suggestedHashtags: ["#CandlestickPatterns", "#TradingEducation", "#MarketWisdom", "#VEDDAi", "#ChartGame"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 3,
    title: "Support & Resistance - Know Your Zones",
    tradingTopic: "Key Price Levels",
    tradingLesson: "Support and resistance are those invisible walls and floors where price likes to bounce. These levels get created by trader psychology - everyone watching the same spots. Learn to draw these zones and youll see the market way different.",
    scriptureReference: "Psalm 18:2",
    scriptureText: "The Lord is my rock and my fortress and my deliverer, my God, my rock, in whom I take refuge.",
    devotionalMessage: "Just like God is our rock and fortress, support levels protect price from falling further. Understanding where these zones hit gives you that confidence when you taking trades.",
    contentPrompt: "Break down support and resistance for your people. Use that rock/fortress metaphor for protection. Show how AI can spot these key levels quick.",
    suggestedHashtags: ["#SupportResistance", "#TechnicalAnalysis", "#TradingLevels", "#VEDDAi", "#ZoneTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 4,
    title: "Trend Is Your Friend - Read The Wave",
    tradingTopic: "Reading Market Direction",
    tradingLesson: "The trend is your homie until the end - dont fight it. Learn to spot uptrends, downtrends, and when the market is just chopping around. Higher highs, higher lows for bulls. Lower highs, lower lows for bears. Simple as that.",
    scriptureReference: "Isaiah 30:21",
    scriptureText: "And your ears shall hear a word behind you, saying, 'This is the way, walk in it,' when you turn to the right or when you turn to the left.",
    devotionalMessage: "God gives direction for our path, and the trend gives direction for our trades. Learning to ride the wave with patience beats fighting the market every time.",
    contentPrompt: "Talk about trend identification and why trading with the trend puts more money in your pocket. Connect to following Gods direction. Show how AI catches trends for you.",
    suggestedHashtags: ["#TrendTrading", "#MarketDirection", "#FaithInTrading", "#VEDDAi", "#RideTheWave"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 5,
    title: "Risk Management - Protect Ya Neck",
    tradingTopic: "Protecting Your Capital",
    tradingLesson: "Real talk - never risk more than 1-2% of your account on one trade. Learn to size your positions based on where your stop loss sits and how big your account is. Keeping your capital safe is priority numero uno. Blow your account and the game is over.",
    scriptureReference: "Proverbs 21:5",
    scriptureText: "The plans of the diligent lead surely to abundance, but everyone who is hasty comes only to poverty.",
    devotionalMessage: "Being diligent means protecting what God blessed you with. Hasty trading without risk management leads to blown accounts. Be a smart steward of your trading bread.",
    contentPrompt: "Put your people on about risk management fr fr. Explain the 1-2% rule and position sizing. Connect it to being a good steward of your blessings.",
    suggestedHashtags: ["#RiskManagement", "#ProtectYaBag", "#CapitalProtection", "#VEDDAi", "#SmartTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 6,
    title: "Stop Loss - Your Trading Insurance",
    tradingTopic: "Setting Protective Stops",
    tradingLesson: "A stop loss is your trading insurance policy. Place stops below support for longs and above resistance for shorts. ATR-based stops are fire because they adapt to how volatile the market is. Protect yourself before you wreck yourself.",
    scriptureReference: "Proverbs 22:3",
    scriptureText: "The prudent sees danger and hides himself, but the simple go on and suffer for it.",
    devotionalMessage: "Smart traders set stop losses to protect themselves from market danger. People who trade without protection get wrecked. Be wise about protecting your capital.",
    contentPrompt: "Talk about why stop losses are non-negotiable. Explain ATR-based stops and how they flex with the market. Emphasize being smart and prepared.",
    suggestedHashtags: ["#StopLoss", "#TradingProtection", "#ATRTrading", "#VEDDAi", "#ProtectYaBag"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 7,
    title: "Week 1 Done - Foundation Solid",
    tradingTopic: "Foundation Week Summary",
    tradingLesson: "Review time: Candlesticks, Support/Resistance, Trends, Risk Management, and Stop Losses. These fundamentals are the pillars, fam. You gotta have these locked before moving to the advanced sauce.",
    scriptureReference: "Matthew 7:24-25",
    scriptureText: "Everyone then who hears these words of mine and does them will be like a wise man who built his house on the rock. And the rain fell, and the floods came, and the winds blew and beat on that house, but it did not fall, because it had been founded on the rock.",
    devotionalMessage: "Week 1 was all about building your trading house on rock. When market storms hit - and they will - your foundational knowledge gonna keep you standing strong.",
    contentPrompt: "Celebrate that Week 1 W! Share the key lessons you learned about trading foundations. Encourage others to start their journey.",
    suggestedHashtags: ["#Week1Done", "#TradingFoundations", "#LevelingUp", "#VEDDAi", "#FoundationFirst"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 1,
    category: "review"
  },
  // Week 2: Strategy Development - Building Your Playbook
  {
    dayNumber: 8,
    title: "Moving Averages - Smooth Out The Noise",
    tradingTopic: "Trend Following Indicators",
    tradingLesson: "Moving averages clean up the messy price action so you can see the real trend. 20 EMA shows short-term vibes, 50 EMA medium-term energy, and 200 EMA is the big picture. Learn those MA crossover signals - they hit different.",
    scriptureReference: "Proverbs 4:25-26",
    scriptureText: "Let your eyes look directly forward, and your gaze be straight before you. Ponder the path of your feet; then all your ways will be sure.",
    devotionalMessage: "Moving averages help you look forward clear, cutting through the daily noise. Keep your eyes on the bigger picture while thinking through each trading move.",
    contentPrompt: "Break down moving averages and why trend traders love them. Show how different timeframe MAs give different insights. Connect to keeping focus on whats ahead.",
    suggestedHashtags: ["#MovingAverages", "#TrendFollowing", "#EMA", "#VEDDAi", "#TradingIndicators"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 9,
    title: "RSI - Reading Momentum Energy",
    tradingTopic: "Momentum Measurement",
    tradingLesson: "RSI measures momentum on a 0-100 scale. Above 70 means the market might be tired from buying, below 30 means sellers might be exhausted. RSI divergence signals are chef's kiss for catching reversals.",
    scriptureReference: "Galatians 6:9",
    scriptureText: "And let us not grow weary of doing good, for in due season we will reap, if we do not give up.",
    devotionalMessage: "RSI shows us when the market is exhausted - when momentum is stretched too far. In trading and life, gotta know when to rest and when to push, trusting Gods timing for the harvest.",
    contentPrompt: "Put your squad on about RSI and spotting overbought/oversold conditions. Connect to not getting tired and waiting for the right season to reap.",
    suggestedHashtags: ["#RSI", "#MomentumTrading", "#TechnicalIndicators", "#VEDDAi", "#OverboughtOversold"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 10,
    title: "MACD - The Trend Momentum Combo",
    tradingTopic: "Trend Momentum Indicator",
    tradingLesson: "MACD shows the relationship between two moving averages. When MACD line crosses above signal line, bulls taking over. When that histogram grows, momentum is picking up steam. Master these signals and you cooking.",
    scriptureReference: "Amos 3:3",
    scriptureText: "Do two walk together, unless they have agreed to meet?",
    devotionalMessage: "MACD shows when price and momentum walking together in agreement. In trading and life, alignment creates power. Trade when signals agree, step back when they beefing.",
    contentPrompt: "Explain MACD and those crossover signals. Use that alignment and agreement concept. Show how VEDD AI catches MACD signals automatic.",
    suggestedHashtags: ["#MACD", "#TradingSignals", "#Momentum", "#VEDDAi", "#IndicatorTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 11,
    title: "Multi-Timeframe - See The Full Picture",
    tradingTopic: "Timeframe Confluence",
    tradingLesson: "Analyze from bigger to smaller timeframes. Daily chart shows the trend, 4H shows structure, 1H shows where to enter. When all timeframes saying the same thing, your confidence gonna be through the roof.",
    scriptureReference: "Proverbs 11:14",
    scriptureText: "Where there is no guidance, a people falls, but in an abundance of counselors there is safety.",
    devotionalMessage: "Multiple timeframes are like counselors, each giving different perspective. Safety comes from gathering input from multiple sources before pulling the trigger.",
    contentPrompt: "Share the power of multi-timeframe analysis. Break down how different timeframes show different things. Connect to seeking wisdom from multiple counselors.",
    suggestedHashtags: ["#MultiTimeframe", "#Confluence", "#TradingWisdom", "#VEDDAi", "#BigPicture"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 12,
    title: "Entry Game - Timing Is Everything",
    tradingTopic: "Timing Your Entry",
    tradingLesson: "The best entries stack multiple confirmations: trend direction, support/resistance levels, indicator signals, and candlestick patterns all lining up. Patience for the A+ setup is key - stop forcing trades that aint there.",
    scriptureReference: "Habakkuk 2:3",
    scriptureText: "For still the vision awaits its appointed time; it hastens to the end—it will not lie. If it seems slow, wait for it; it will surely come; it will not delay.",
    devotionalMessage: "Wait for your trading setup like waiting for a vision to come through. The best entries come to those who patient for everything to line up. Rushing in leads to L's.",
    contentPrompt: "Talk about patience in waiting for quality entries. Explain confluence and stacking confirmations. Connect to waiting for Gods appointed time.",
    suggestedHashtags: ["#TradeEntry", "#PatientTrading", "#Confluence", "#VEDDAi", "#A+Setups"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 13,
    title: "Take Profit - Know When To Cash Out",
    tradingTopic: "Exit Strategy Planning",
    tradingLesson: "Plan your exits before you even get in. Use previous highs/lows, Fibonacci extensions, and risk-reward ratios to set them take profit targets. Taking partial profits along the way can lock in gains while letting winners run.",
    scriptureReference: "Luke 14:28",
    scriptureText: "For which of you, desiring to build a tower, does not first sit down and count the cost, whether he has enough to complete it?",
    devotionalMessage: "Counting the cost includes knowing when youre out. Plan your take profits before entering, just like a builder plans before breaking ground.",
    contentPrompt: "Share strategies for setting take profit levels. Explain why planning exits before entries is the wave. Connect to counting the cost and planning ahead.",
    suggestedHashtags: ["#TakeProfit", "#ExitStrategy", "#TradingPlan", "#VEDDAi", "#CashOut"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 14,
    title: "Week 2 Complete - Strategy Unlocked",
    tradingTopic: "Strategy Week Summary",
    tradingLesson: "Review: Moving Averages, RSI, MACD, Multi-Timeframe Analysis, Entry Strategies, and Take Profit Planning. You now got the tools to build a complete trading strategy. Thats a W.",
    scriptureReference: "James 1:4",
    scriptureText: "And let steadfastness have its full effect, that you may be perfect and complete, lacking in nothing.",
    devotionalMessage: "Week 2 added powerful tools to your arsenal. Let that consistency in learning have its full effect. Youre becoming more complete as a trader every day.",
    contentPrompt: "Celebrate Week 2 completion! Share progress on learning indicators and strategy development. Encourage consistency and steady grinding.",
    suggestedHashtags: ["#Week2Done", "#StrategyDevelopment", "#TradingGrowth", "#VEDDAi", "#LevelUp"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 2,
    category: "review"
  },
  // Week 3: Trading Mindset - Master Your Mental
  {
    dayNumber: 15,
    title: "Trading Psychology - Control Your Mind",
    tradingTopic: "Mastering Your Mind",
    tradingLesson: "Your biggest enemy in trading is yourself. Fear makes you exit too early, greed makes you stay too long. Develop emotional discipline through journaling and self-awareness. The mind game is everything.",
    scriptureReference: "2 Timothy 1:7",
    scriptureText: "For God gave us a spirit not of fear but of power and love and self-control.",
    devotionalMessage: "God didnt give us fear - He gave us power and self-control. Apply that same energy to trading. Master your emotions and youll master the markets.",
    contentPrompt: "Talk about the mental side of trading. Share how to overcome fear and greed. Connect to the spirit of power and self-control God gave us.",
    suggestedHashtags: ["#TradingPsychology", "#MindsetMatters", "#EmotionalControl", "#VEDDAi", "#TraderMindset"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 16,
    title: "Patience Pays - Wait For Your Setup",
    tradingTopic: "Developing Patience",
    tradingLesson: "The best traders are the most patient. Waiting for A+ setups means less trades but higher win rate. Quality over quantity every time. Let the trade come to you.",
    scriptureReference: "Psalm 37:7",
    scriptureText: "Be still before the Lord and wait patiently for him; fret not yourself over the one who prospers in his way.",
    devotionalMessage: "Being still and patient is hard when you see others winning. But your setups are different than theirs. Trust your process and wait for your moments.",
    contentPrompt: "Share about the power of patience in trading. Explain why waiting for quality setups beats overtrading. Connect to being still and trusting the process.",
    suggestedHashtags: ["#TradingPatience", "#QualityOverQuantity", "#WaitForIt", "#VEDDAi", "#A+Setups"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 17,
    title: "Handling Losses - They Part Of The Game",
    tradingTopic: "Loss Management",
    tradingLesson: "Every trader takes Ls - its part of the game. What separates winners is how they respond. Take the loss, learn the lesson, move on. Dont revenge trade, dont tilt, dont let one loss turn into five.",
    scriptureReference: "Proverbs 24:16",
    scriptureText: "For the righteous falls seven times and rises again, but the wicked stumble in times of calamity.",
    devotionalMessage: "Falling isnt failing - staying down is. When you take a trading loss, rise again with new wisdom. Each loss is a lesson if youre paying attention.",
    contentPrompt: "Talk about handling trading losses the right way. Share your personal experience with losses and recovery. Connect to rising again after falling.",
    suggestedHashtags: ["#TradingLosses", "#BounceBack", "#LessonsLearned", "#VEDDAi", "#TraderResilience"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 18,
    title: "FOMO Is The Enemy - Stay In Your Lane",
    tradingTopic: "Avoiding FOMO Trading",
    tradingLesson: "FOMO (Fear Of Missing Out) will wreck your account faster than anything. Seeing a move you missed and jumping in late is how you get burned. There will always be another trade. Stay disciplined.",
    scriptureReference: "Proverbs 14:29",
    scriptureText: "Whoever is slow to anger has great understanding, but he who has a hasty temper exalts folly.",
    devotionalMessage: "Being slow to react and quick to think shows understanding. Hasty entries driven by FOMO is straight folly. Stay in your lane and trade your plan.",
    contentPrompt: "Warn your people about the dangers of FOMO trading. Share a FOMO story and what you learned. Connect to the wisdom of patience over hasty reactions.",
    suggestedHashtags: ["#NoFOMO", "#TradingDiscipline", "#StayInYourLane", "#VEDDAi", "#PatientTrader"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 19,
    title: "Trading Journal - Track Your Moves",
    tradingTopic: "Journaling Your Trades",
    tradingLesson: "A trading journal is your personal playbook for improvement. Record every trade: entry, exit, why you took it, how you felt. Review weekly to spot patterns in your wins and losses.",
    scriptureReference: "Lamentations 3:40",
    scriptureText: "Let us test and examine our ways, and return to the Lord!",
    devotionalMessage: "Self-examination leads to growth. Testing and examining your trading ways through journaling reveals patterns you cant see otherwise. Reflection is key to improvement.",
    contentPrompt: "Share the importance of keeping a trading journal. Show what you track and how it helps. Connect to self-examination and growth.",
    suggestedHashtags: ["#TradingJournal", "#TrackYourTrades", "#SelfImprovement", "#VEDDAi", "#TraderGrowth"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 20,
    title: "Consistency Over Everything",
    tradingTopic: "Building Consistent Habits",
    tradingLesson: "Consistency beats intensity every time. Trading the same strategy, same risk, same routine daily builds the discipline needed for long-term success. One fire week means nothing if you cant sustain it.",
    scriptureReference: "1 Corinthians 9:27",
    scriptureText: "But I discipline my body and keep it under control, lest after preaching to others I myself should be disqualified.",
    devotionalMessage: "Discipline your trading like an athlete disciplines their body. Keep yourself under control daily. Consistency is what separates pros from amateurs.",
    contentPrompt: "Talk about the power of consistency in trading. Share your daily routine and habits. Connect to disciplining yourself for long-term success.",
    suggestedHashtags: ["#Consistency", "#TradingHabits", "#DailyDiscipline", "#VEDDAi", "#TraderRoutine"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 21,
    title: "Week 3 Complete - Mindset On Point",
    tradingTopic: "Mindset Week Summary",
    tradingLesson: "Review: Psychology, Patience, Loss Management, FOMO Avoidance, Journaling, and Consistency. Your mind is now as sharp as your strategy. Thats the complete package.",
    scriptureReference: "Romans 12:2",
    scriptureText: "Do not be conformed to this world, but be transformed by the renewal of your mind.",
    devotionalMessage: "Week 3 was all about renewing your trading mind. Dont conform to amateur habits - transform through wisdom and discipline. Your mindset is renewed.",
    contentPrompt: "Celebrate Week 3 completion! Share how your trading mindset has transformed. Encourage others to work on their mental game.",
    suggestedHashtags: ["#Week3Done", "#MindsetTransformed", "#TradingMentalGame", "#VEDDAi", "#RenewedMind"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 3,
    category: "review"
  },
  // Week 4: Trade Execution - Time To Execute
  {
    dayNumber: 22,
    title: "Pre-Trade Checklist - Run The Checks",
    tradingTopic: "Trade Preparation",
    tradingLesson: "Before every trade, run your checklist: Is the trend confirmed? Are you at a key level? Do indicators agree? Is risk calculated? Never skip the checklist - it saves you from emotional trades.",
    scriptureReference: "Proverbs 16:3",
    scriptureText: "Commit your work to the Lord, and your plans will be established.",
    devotionalMessage: "Commit your trading to the Lord and establish your plans through proper preparation. A pre-trade checklist is your plan in action.",
    contentPrompt: "Share your pre-trade checklist with your audience. Explain why each item matters. Connect to committing work to God and establishing plans.",
    suggestedHashtags: ["#PreTradeChecklist", "#TradingPreparation", "#TradeSetup", "#VEDDAi", "#TradeSmart"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 23,
    title: "Order Types - Know Your Options",
    tradingTopic: "Understanding Order Types",
    tradingLesson: "Market orders fill instant but you get whatever price. Limit orders let you set your price but might not fill. Stop orders trigger when price hits your level. Know when to use each.",
    scriptureReference: "Proverbs 21:29",
    scriptureText: "A wicked man puts on a bold face, but the upright gives thought to his ways.",
    devotionalMessage: "Give thought to how you enter trades. Understanding order types means you control your entries instead of just market buying blindly.",
    contentPrompt: "Explain the different order types and when to use them. Share which you prefer and why. Connect to giving thought to your ways.",
    suggestedHashtags: ["#OrderTypes", "#TradingExecution", "#LimitOrders", "#VEDDAi", "#SmartEntries"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 24,
    title: "Position Sizing - Right Size Your Trades",
    tradingTopic: "Calculating Position Size",
    tradingLesson: "Position sizing is how you control risk on every trade. Formula: Risk Amount / Stop Loss Distance = Position Size. Never eyeball it - calculate it every time. This is how pros protect capital.",
    scriptureReference: "Luke 16:10",
    scriptureText: "One who is faithful in a very little is also faithful in much, and one who is dishonest in a very little is also dishonest in much.",
    devotionalMessage: "Be faithful in sizing your trades correctly, even on small accounts. Master position sizing now and itll serve you when your account grows.",
    contentPrompt: "Break down position sizing and the formula. Show a real calculation example. Connect to being faithful in small things.",
    suggestedHashtags: ["#PositionSizing", "#RiskCalculation", "#TradeMath", "#VEDDAi", "#ProperSizing"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 25,
    title: "Trade Management - Active Management",
    tradingTopic: "Managing Open Positions",
    tradingLesson: "Once youre in a trade, the job isnt done. Know when to move stop loss to breakeven, when to take partial profits, when to let it ride. Active management turns good trades into great trades.",
    scriptureReference: "Proverbs 27:23",
    scriptureText: "Know well the condition of your flocks, and give attention to your herds.",
    devotionalMessage: "Know the condition of your open trades like a shepherd knows their flock. Give attention to whats happening and manage actively.",
    contentPrompt: "Share trade management techniques - trailing stops, partials, breakeven. Explain when to use each. Connect to knowing and managing whats yours.",
    suggestedHashtags: ["#TradeManagement", "#ActiveTrading", "#TrailingStop", "#VEDDAi", "#ManageYourTrades"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 26,
    title: "Scaling In & Out - Layer Your Trades",
    tradingTopic: "Scaling Strategies",
    tradingLesson: "Scaling in means adding to a winning position at better prices. Scaling out means taking partial profits as price moves your way. Both strategies reduce risk and lock in gains.",
    scriptureReference: "Ecclesiastes 11:2",
    scriptureText: "Give a portion to seven, or even to eight, for you know not what disaster may happen on earth.",
    devotionalMessage: "Diversify your entries and exits across multiple levels. You dont know what the market will do, so spread your risk wisely.",
    contentPrompt: "Explain scaling in and scaling out strategies. Share when each makes sense. Connect to diversifying and managing uncertainty.",
    suggestedHashtags: ["#ScalingIn", "#ScalingOut", "#TradingStrategy", "#VEDDAi", "#RiskManagement"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 27,
    title: "News Trading - Handle The Volatility",
    tradingTopic: "Trading Around News Events",
    tradingLesson: "News events create crazy volatility. Know the economic calendar, widen stops or stay flat during major announcements. FOMC, NFP, CPI - these events move markets hard. Respect the risk.",
    scriptureReference: "Proverbs 22:7",
    scriptureText: "The prudent sees danger and hides himself, but the simple go on and suffer for it.",
    devotionalMessage: "Prudent traders see news events coming and protect themselves. The simple ignore the calendar and get stopped out by volatility spikes.",
    contentPrompt: "Share how to handle trading around major news events. Explain the economic calendar importance. Connect to seeing danger and being prepared.",
    suggestedHashtags: ["#NewsTrading", "#EconomicCalendar", "#Volatility", "#VEDDAi", "#TradeSmart"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 28,
    title: "Week 4 Complete - Execution Mode",
    tradingTopic: "Execution Week Summary",
    tradingLesson: "Review: Checklists, Order Types, Position Sizing, Trade Management, Scaling, and News Trading. You now know how to execute trades like a pro. Knowledge is power - go use it.",
    scriptureReference: "James 1:22",
    scriptureText: "But be doers of the word, and not hearers only, deceiving yourselves.",
    devotionalMessage: "Dont just hear this teaching - do it. Apply what youve learned about execution. Knowledge without action is useless.",
    contentPrompt: "Celebrate Week 4 completion! Share how your trade execution has improved. Encourage others to put knowledge into action.",
    suggestedHashtags: ["#Week4Done", "#ExecutionMode", "#TradingSkills", "#VEDDAi", "#DoersNotHearers"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 4,
    category: "review"
  },
  // Week 5: Advanced Concepts - Level Up
  {
    dayNumber: 29,
    title: "Fibonacci Levels - The Golden Ratio",
    tradingTopic: "Fibonacci Retracements",
    tradingLesson: "Fibonacci levels are based on the golden ratio found everywhere in nature. The 38.2%, 50%, and 61.8% retracement levels are where price often bounces. These levels are spooky accurate.",
    scriptureReference: "Psalm 19:1",
    scriptureText: "The heavens declare the glory of God, and the sky above proclaims his handiwork.",
    devotionalMessage: "Gods mathematical patterns appear in the heavens, in nature, and yes, in the markets. Fibonacci levels reflect divine order in chaos.",
    contentPrompt: "Break down Fibonacci retracements and why they work. Show examples of price bouncing at Fib levels. Connect to Gods mathematical order in creation.",
    suggestedHashtags: ["#Fibonacci", "#GoldenRatio", "#TradingMath", "#VEDDAi", "#FibLevels"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 30,
    title: "Supply & Demand Zones - Where Big Money Plays",
    tradingTopic: "Institutional Order Flow",
    tradingLesson: "Supply and demand zones show where big money placed orders. Price often returns to these areas before continuing. Theyre like support/resistance but more precise. Learn to spot them.",
    scriptureReference: "Proverbs 13:22",
    scriptureText: "A good man leaves an inheritance to his children's children, but the sinner's wealth is laid up for the righteous.",
    devotionalMessage: "Institutions leave footprints in the charts through supply and demand zones. Learn to read where big money is positioned.",
    contentPrompt: "Explain supply and demand zones and how to identify them. Show how institutions leave traces on charts. Connect to understanding where wealth flows.",
    suggestedHashtags: ["#SupplyDemand", "#InstitutionalTrading", "#OrderFlow", "#VEDDAi", "#BigMoneyMoves"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 31,
    title: "Volume Analysis - Follow The Money",
    tradingTopic: "Reading Volume",
    tradingLesson: "Volume confirms price moves. High volume on a breakout means its real. Low volume on a move means it might reverse. Volume is like truth serum for price action.",
    scriptureReference: "Matthew 6:21",
    scriptureText: "For where your treasure is, there your heart will be also.",
    devotionalMessage: "Volume shows where traders put their money - their treasure. High volume reveals commitment. Low volume reveals hesitation. Follow the money.",
    contentPrompt: "Share how to read volume to confirm trades. Explain what high and low volume mean. Connect to following where treasure is placed.",
    suggestedHashtags: ["#VolumeAnalysis", "#FollowTheMoney", "#TradingConfirmation", "#VEDDAi", "#VolumeTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 32,
    title: "Chart Patterns - The Classics",
    tradingTopic: "Pattern Recognition",
    tradingLesson: "Head and shoulders, double tops/bottoms, triangles, flags - these patterns repeat because human psychology repeats. Learn the classics and youll see setups everywhere.",
    scriptureReference: "Ecclesiastes 1:9",
    scriptureText: "What has been is what will be, and what has been done is what will be done, and there is nothing new under the sun.",
    devotionalMessage: "Nothing new under the sun - including chart patterns. Human behavior creates the same patterns generation after generation. History rhymes.",
    contentPrompt: "Break down classic chart patterns and what they signal. Show examples of patterns playing out. Connect to patterns repeating through history.",
    suggestedHashtags: ["#ChartPatterns", "#PatternRecognition", "#TechnicalAnalysis", "#VEDDAi", "#ClassicPatterns"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 33,
    title: "Divergence Trading - Hidden Signals",
    tradingTopic: "RSI & MACD Divergence",
    tradingLesson: "Divergence happens when price makes new highs but indicators dont confirm. Its a warning sign of potential reversal. Hidden divergence signals trend continuation. Both are powerful.",
    scriptureReference: "Proverbs 20:12",
    scriptureText: "The hearing ear and the seeing eye, the Lord has made them both.",
    devotionalMessage: "God gave us eyes to see what others miss. Divergence is a hidden signal that most traders dont catch. Train your eyes to see the invisible.",
    contentPrompt: "Explain divergence trading and how to spot it. Show examples of regular and hidden divergence. Connect to seeing what others miss.",
    suggestedHashtags: ["#Divergence", "#HiddenSignals", "#RSIDivergence", "#VEDDAi", "#AdvancedTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 34,
    title: "Market Structure - Reading The Blueprint",
    tradingTopic: "Understanding Market Structure",
    tradingLesson: "Market structure is the blueprint of price movement. Higher highs and higher lows in uptrend. Lower highs and lower lows in downtrend. Break of structure signals a change. Read the blueprint.",
    scriptureReference: "1 Corinthians 14:40",
    scriptureText: "But all things should be done decently and in order.",
    devotionalMessage: "Markets have order and structure, even when they look chaotic. Learn to read that order and trade with the structure, not against it.",
    contentPrompt: "Break down market structure and how to identify changes. Show break of structure examples. Connect to finding order in apparent chaos.",
    suggestedHashtags: ["#MarketStructure", "#PriceAction", "#TradingBlueprint", "#VEDDAi", "#StructureTrading"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 35,
    title: "Week 5 Complete - Advanced Mode Unlocked",
    tradingTopic: "Advanced Concepts Summary",
    tradingLesson: "Review: Fibonacci, Supply/Demand, Volume, Chart Patterns, Divergence, and Market Structure. You now have advanced tools most traders never learn. Use them wisely.",
    scriptureReference: "Proverbs 24:5",
    scriptureText: "A wise man is full of strength, and a man of knowledge enhances his might.",
    devotionalMessage: "Week 5 filled you with advanced knowledge that enhances your trading strength. Wisdom and knowledge together create power. Youre leveling up.",
    contentPrompt: "Celebrate Week 5 completion! Share your favorite advanced concept. Encourage others to push beyond basics.",
    suggestedHashtags: ["#Week5Done", "#AdvancedTrading", "#LeveledUp", "#VEDDAi", "#TradingMastery"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 5,
    category: "review"
  },
  // Week 6: Building Your Business - Ambassador Life
  {
    dayNumber: 36,
    title: "Creating Trading Content - Share Your Journey",
    tradingTopic: "Content Creation Basics",
    tradingLesson: "Your trading journey is content gold. Share your analyses, your wins, your lessons. Authenticity beats perfection. Start creating and posting consistently.",
    scriptureReference: "Matthew 5:14-15",
    scriptureText: "You are the light of the world. A city set on a hill cannot be hidden. Nor do people light a lamp and put it under a basket.",
    devotionalMessage: "Dont hide your trading knowledge - share it. Your light can guide others on their journey. Be the city on the hill for aspiring traders.",
    contentPrompt: "Share tips for creating trading content. Encourage authenticity over perfection. Connect to being a light and not hiding your knowledge.",
    suggestedHashtags: ["#ContentCreation", "#TradingContent", "#ShareYourJourney", "#VEDDAi", "#BeTheLight"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 6,
    category: "execution"
  },
  {
    dayNumber: 37,
    title: "Building Your VEDD Tribe - Community First",
    tradingTopic: "Community Building",
    tradingLesson: "VEDD is an Online University-style community experience, not just a trading tool. Your role is to build a supportive tribe where traders learn together, hold each other accountable, and celebrate wins as a family. Start with quality over quantity - 10 committed members beats 100 passive ones.",
    scriptureReference: "Proverbs 11:25",
    scriptureText: "Whoever brings blessing will be enriched, and one who waters will himself be watered.",
    devotionalMessage: "Bless your community with knowledge and support, and youll be blessed in return. Water others with value and watch your tribe flourish. Community building is an investment that compounds.",
    contentPrompt: "Share your vision for building a VEDD trading community. Explain why community matters for trader success. Talk about the Online University experience VEDD provides - courses, live events, mentorship, and shared growth.",
    suggestedHashtags: ["#VEDDCommunity", "#TradingTribe", "#OnlineUniversity", "#VEDDAi", "#CommunityFirst"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 6,
    category: "execution"
  },
  {
    dayNumber: 38,
    title: "Hosting Your First VEDD Community Event",
    tradingTopic: "Event Hosting",
    tradingLesson: "Use VEDDs Host Dashboard to create live events for your community. Start with a simple Chart Review session - walk through AI analysis of a chart, answer questions, and show the platform in action. Record everything so people who missed it can catch the replay.",
    scriptureReference: "Hebrews 10:24-25",
    scriptureText: "And let us consider how to stir up one another to love and good works, not neglecting to meet together.",
    devotionalMessage: "Live community events are modern gatherings where we encourage and teach each other. Dont neglect bringing your tribe together - both online and in real time.",
    contentPrompt: "Announce your first community event! Share what youll cover (live chart analysis, Q&A, platform demo). Invite people to join and be part of something special. Talk about the power of gathering together.",
    suggestedHashtags: ["#VEDDLive", "#CommunityEvent", "#TradingTogether", "#VEDDAi", "#JoinTheTribe"],
    mediaType: "video",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 6,
    category: "execution"
  },
  {
    dayNumber: 39,
    title: "Member Spotlights - Celebrate Your Tribe",
    tradingTopic: "Community Recognition",
    tradingLesson: "Recognize and celebrate your community members! Spotlight traders who hit milestones - first chart analysis, first EA created, 30-day streak. Share their success stories with permission. When you celebrate others, they become your biggest advocates.",
    scriptureReference: "Romans 12:15",
    scriptureText: "Rejoice with those who rejoice, weep with those who weep.",
    devotionalMessage: "True community means celebrating each others wins and supporting through losses. When your tribe member hits a milestone, make it a big deal. Their success is your success.",
    contentPrompt: "Create a member spotlight post! Celebrate a community members achievement (with permission). Share their journey, their wins, and how VEDD helped. Encourage others to share their stories too.",
    suggestedHashtags: ["#MemberSpotlight", "#VEDDWins", "#CelebrateTogether", "#VEDDAi", "#CommunityLove"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 6,
    category: "execution"
  },
  {
    dayNumber: 40,
    title: "Accountability Partners - Trading Buddies",
    tradingTopic: "Peer Accountability",
    tradingLesson: "Help community members find accountability partners - trading buddies who check in on each others discipline. Set up simple check-ins: Did you follow your risk rules? Did you journal your trades? Did you stick to your strategy? This buddy system keeps traders on track.",
    scriptureReference: "Ecclesiastes 4:9-10",
    scriptureText: "Two are better than one, because they have a good reward for their toil. For if they fall, one will lift up his fellow.",
    devotionalMessage: "Two traders are better than one. When you fall into bad habits, your accountability partner lifts you up. Build this into your community culture.",
    contentPrompt: "Introduce the accountability partner concept! Share how trading buddies help each other stay disciplined. Encourage community members to pair up. Explain the simple check-in system.",
    suggestedHashtags: ["#AccountabilityPartner", "#TradingBuddy", "#DisciplineMatters", "#VEDDAi", "#BetterTogether"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 6,
    category: "execution"
  },
  {
    dayNumber: 41,
    title: "Welcoming New Members - First Impressions",
    tradingTopic: "Member Onboarding",
    tradingLesson: "First impressions make or break retention. Send every new member a personal welcome message within 24 hours. Ask about their trading experience and goals. Guide them to their first chart analysis. Make them feel like they just joined a family, not signed up for software.",
    scriptureReference: "Romans 15:7",
    scriptureText: "Therefore welcome one another as Christ has welcomed you, for the glory of God.",
    devotionalMessage: "Welcome new members the way you would want to be welcomed. Personal attention creates belonging. That 5-minute welcome message can create a lifelong community member.",
    contentPrompt: "Share your new member welcome process! Explain why personal outreach matters. Give tips for making newcomers feel valued. Talk about the VEDD family culture.",
    suggestedHashtags: ["#WelcomeToTheFamily", "#NewMember", "#VEDDFamily", "#VEDDAi", "#FirstImpressions"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 6,
    category: "execution"
  },
  {
    dayNumber: 42,
    title: "Week 6 Complete - Community Builder",
    tradingTopic: "Community Building Summary",
    tradingLesson: "Review: Building your VEDD tribe, hosting community events, member spotlights, accountability partners, and welcoming new members. Youre now equipped to build and nurture a thriving trading community around the VEDD Online University experience.",
    scriptureReference: "2 Timothy 2:2",
    scriptureText: "And what you have heard from me in the presence of many witnesses entrust to faithful men, who will be able to teach others also.",
    devotionalMessage: "What youve learned about community building, now pass on to others. Train faithful community members who will continue growing and nurturing the tribe. Thats the VEDD ambassador mission.",
    contentPrompt: "Celebrate Week 6 as a Community Building master! Share what youve learned about building tribes, hosting events, and welcoming members. Encourage others to focus on community first.",
    suggestedHashtags: ["#Week6Done", "#CommunityBuilder", "#VEDDTribe", "#VEDDAi", "#OnlineUniversity"],
    mediaType: "carousel",
    tokenReward: 25,
    bonusTokens: 15,
    weekNumber: 6,
    category: "review"
  },
  // Final Days: Certification & Celebration
  {
    dayNumber: 43,
    title: "Final Review - Everything Youve Learned",
    tradingTopic: "Complete Program Review",
    tradingLesson: "Review all 6 weeks: Foundation, Strategy, Mindset, Execution, Advanced Concepts, and Ambassador Business. You have a complete trading education and the tools to share it.",
    scriptureReference: "Philippians 3:14",
    scriptureText: "I press on toward the goal for the prize of the upward call of God in Christ Jesus.",
    devotionalMessage: "Youve pressed on through 43 days of training. The goal is in sight. Keep pressing toward the prize of being a certified ambassador.",
    contentPrompt: "Create a comprehensive review of your 43-day journey. Share key takeaways from each week. Inspire others to start their journey.",
    suggestedHashtags: ["#FinalReview", "#43DaysComplete", "#TradingJourney", "#VEDDAi", "#PressOn"],
    mediaType: "carousel",
    tokenReward: 25,
    bonusTokens: 15,
    weekNumber: 7,
    category: "review"
  },
  {
    dayNumber: 44,
    title: "Graduation Day - Youre Certified!",
    tradingTopic: "Ambassador Certification",
    tradingLesson: "Congratulations! You completed the 44-day Ambassador Training Program. Youre now a Certified VEDD AI Ambassador with the knowledge, skills, and authority to represent the platform.",
    scriptureReference: "2 Timothy 4:7-8",
    scriptureText: "I have fought the good fight, I have finished the race, I have kept the faith. Henceforth there is laid up for me the crown of righteousness.",
    devotionalMessage: "You fought the good fight of learning, you finished the 44-day race, you kept faith in the process. Your crown awaits - wear your certification with honor.",
    contentPrompt: "Celebrate your graduation! Share your certification achievement. Encourage others to start their 44-day journey. Youre officially an ambassador.",
    suggestedHashtags: ["#GraduationDay", "#CertifiedAmbassador", "#VEDDAi", "#FinishedTheRace", "#AmbassadorLife"],
    mediaType: "video",
    tokenReward: 50,
    bonusTokens: 50,
    weekNumber: 7,
    category: "review"
  }
];

export default { ambassadorContentCurriculum };
