export interface DailyLessonData {
  dayNumber: number;
  title: string;
  tradingTopic: string;
  tradingLesson: string;
  scriptureReference: string;
  scriptureText: string;
  devotionalMessage: string;
  contentPrompt: string;
  suggestedHashtags: string[];
  mediaType: 'image' | 'video' | 'carousel';
  tokenReward: number;
  bonusTokens: number;
  weekNumber: number;
  category: 'foundation' | 'strategy' | 'mindset' | 'execution' | 'review';
}

export const ambassadorContentCurriculum: DailyLessonData[] = [
  // Week 1: Foundation
  {
    dayNumber: 1,
    title: "Your Trading Journey Begins",
    tradingTopic: "Introduction to Chart Analysis",
    tradingLesson: "Every successful trader starts with understanding how to read charts. Today, learn the basics of candlestick patterns - the building blocks of price action analysis.",
    scriptureReference: "Proverbs 24:27",
    scriptureText: "Prepare your work outside; get everything ready for yourself in the field, and after that build your house.",
    devotionalMessage: "Just as Scripture teaches us to prepare before building, successful trading requires a solid foundation. Start with the basics, master them, and build your strategy on a firm foundation.",
    contentPrompt: "Create an inspiring social media post about starting a trading journey with proper preparation. Mention the importance of learning chart basics before trading real money. Include a faith-based message about building on solid foundations.",
    suggestedHashtags: ["#TradingJourney", "#ChartAnalysis", "#FaithAndFinance", "#VEDDAi", "#TradingWisdom"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 2,
    title: "Understanding Candlesticks",
    tradingTopic: "Candlestick Patterns Basics",
    tradingLesson: "Candlesticks tell stories of buyer and seller battles. Learn to identify bullish engulfing, bearish engulfing, and doji patterns - the three patterns that reveal market indecision and momentum shifts.",
    scriptureReference: "Ecclesiastes 3:1",
    scriptureText: "For everything there is a season, and a time for every matter under heaven.",
    devotionalMessage: "Markets have seasons too - times to buy, times to sell, times to wait. Wisdom is knowing which season you're in. Let candlestick patterns guide you to recognize the market's current season.",
    contentPrompt: "Share educational content about candlestick patterns and their meanings. Connect it to the biblical concept of seasons and timing. Encourage followers to learn pattern recognition.",
    suggestedHashtags: ["#CandlestickPatterns", "#TradingEducation", "#MarketWisdom", "#VEDDAi", "#PatternTrading"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 3,
    title: "Support & Resistance",
    tradingTopic: "Key Price Levels",
    tradingLesson: "Support and resistance levels are where price action pauses or reverses. These invisible walls and floors are created by collective trader psychology. Learn to identify and draw these critical levels.",
    scriptureReference: "Psalm 18:2",
    scriptureText: "The Lord is my rock and my fortress and my deliverer, my God, my rock, in whom I take refuge.",
    devotionalMessage: "Just as God is our rock and fortress, support levels in trading provide protection from price falling further. Understanding where these levels exist gives us confidence in our trading decisions.",
    contentPrompt: "Create content explaining support and resistance levels in trading. Use the metaphor of a rock/fortress for protection. Share how AI can help identify these key levels.",
    suggestedHashtags: ["#SupportResistance", "#TechnicalAnalysis", "#TradingLevels", "#VEDDAi", "#ChartAnalysis"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 4,
    title: "Trend Identification",
    tradingTopic: "Reading Market Direction",
    tradingLesson: "The trend is your friend until the end. Learn to identify uptrends, downtrends, and ranging markets using higher highs, higher lows, lower highs, and lower lows.",
    scriptureReference: "Isaiah 30:21",
    scriptureText: "And your ears shall hear a word behind you, saying, 'This is the way, walk in it,' when you turn to the right or when you turn to the left.",
    devotionalMessage: "God provides direction for our path, and in trading, the trend provides direction for our trades. Learning to follow the trend with patience yields greater results than fighting against the market's momentum.",
    contentPrompt: "Share about trend identification and why trading with the trend leads to better results. Connect to the biblical principle of following God's direction. Highlight how AI helps identify trends accurately.",
    suggestedHashtags: ["#TrendTrading", "#MarketDirection", "#FaithInTrading", "#VEDDAi", "#TechnicalAnalysis"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 5,
    title: "Risk Management Basics",
    tradingTopic: "Protecting Your Capital",
    tradingLesson: "Never risk more than 1-2% of your account on a single trade. Learn to calculate position size based on your stop loss distance and account size. Preservation of capital is priority #1.",
    scriptureReference: "Proverbs 21:5",
    scriptureText: "The plans of the diligent lead surely to abundance, but everyone who is hasty comes only to poverty.",
    devotionalMessage: "Diligent planning includes protecting what God has entrusted to us. Hasty trading without proper risk management leads to account destruction. Be a diligent steward of your trading capital.",
    contentPrompt: "Create content about the importance of risk management in trading. Emphasize the 1-2% rule and position sizing. Connect to biblical stewardship principles.",
    suggestedHashtags: ["#RiskManagement", "#TradingSafety", "#CapitalProtection", "#VEDDAi", "#SmartTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 6,
    title: "Stop Loss Strategy",
    tradingTopic: "Setting Protective Stops",
    tradingLesson: "A stop loss is your trading insurance. Learn to place stops below support for longs and above resistance for shorts. ATR-based stops adapt to market volatility for better protection.",
    scriptureReference: "Proverbs 22:3",
    scriptureText: "The prudent sees danger and hides himself, but the simple go on and suffer for it.",
    devotionalMessage: "Prudent traders set stop losses to protect themselves from market danger. The simple trader trades without protection and suffers devastating losses. Be prudent in your trading approach.",
    contentPrompt: "Share about the critical importance of stop losses. Explain how ATR-based stops adapt to different market conditions. Emphasize being prudent and prepared.",
    suggestedHashtags: ["#StopLoss", "#TradingProtection", "#ATRTrading", "#VEDDAi", "#RiskManagement"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 1,
    category: "foundation"
  },
  {
    dayNumber: 7,
    title: "Week 1 Review",
    tradingTopic: "Foundation Week Summary",
    tradingLesson: "Review: Candlesticks, Support/Resistance, Trends, Risk Management, and Stop Losses. These fundamentals are the pillars of successful trading. Master these before moving to advanced strategies.",
    scriptureReference: "Matthew 7:24-25",
    scriptureText: "Everyone then who hears these words of mine and does them will be like a wise man who built his house on the rock. And the rain fell, and the floods came, and the winds blew and beat on that house, but it did not fall, because it had been founded on the rock.",
    devotionalMessage: "Week 1 has been about building your trading foundation on rock. When market storms come - and they will - your foundational knowledge will keep you standing strong.",
    contentPrompt: "Create a week 1 summary post celebrating progress. Highlight the key lessons learned about trading foundations. Encourage others to start their learning journey.",
    suggestedHashtags: ["#Week1Complete", "#TradingFoundations", "#LearningJourney", "#VEDDAi", "#TradingEducation"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 1,
    category: "review"
  },
  // Week 2: Strategy Development
  {
    dayNumber: 8,
    title: "Moving Averages",
    tradingTopic: "Trend Following Indicators",
    tradingLesson: "Moving averages smooth price action to reveal trends. The 20 EMA shows short-term momentum, 50 EMA medium-term, and 200 EMA long-term direction. Learn MA crossover signals.",
    scriptureReference: "Proverbs 4:25-26",
    scriptureText: "Let your eyes look directly forward, and your gaze be straight before you. Ponder the path of your feet; then all your ways will be sure.",
    devotionalMessage: "Moving averages help us look forward with clarity, smoothing out the noise of daily fluctuations. Keep your eyes on the bigger picture while pondering each trading decision.",
    contentPrompt: "Explain moving averages and their importance in trend following. Share how different timeframe MAs provide different insights. Connect to maintaining focus on the path ahead.",
    suggestedHashtags: ["#MovingAverages", "#TrendFollowing", "#EMA", "#VEDDAi", "#TradingIndicators"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 9,
    title: "RSI Indicator",
    tradingTopic: "Momentum Measurement",
    tradingLesson: "RSI measures momentum on a 0-100 scale. Above 70 suggests overbought conditions, below 30 oversold. Learn to spot RSI divergence for powerful reversal signals.",
    scriptureReference: "Galatians 6:9",
    scriptureText: "And let us not grow weary of doing good, for in due season we will reap, if we do not give up.",
    devotionalMessage: "RSI teaches us about market exhaustion - when momentum is overextended. Similarly, in life and trading, we must recognize when to rest and when to push forward, trusting God's timing for our harvest.",
    contentPrompt: "Share educational content about RSI indicator and identifying overbought/oversold conditions. Connect to the concept of not growing weary and waiting for the right season.",
    suggestedHashtags: ["#RSI", "#MomentumTrading", "#TechnicalIndicators", "#VEDDAi", "#OverboughtOversold"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 10,
    title: "MACD Signals",
    tradingTopic: "Trend Momentum Indicator",
    tradingLesson: "MACD shows the relationship between two moving averages. When MACD line crosses above signal line, it's bullish. When histogram grows, momentum is increasing. Master these signals.",
    scriptureReference: "Amos 3:3",
    scriptureText: "Do two walk together, unless they have agreed to meet?",
    devotionalMessage: "MACD shows when price and momentum are walking together in agreement. In trading and life, alignment creates power. Trade when signals agree, step back when they conflict.",
    contentPrompt: "Explain the MACD indicator and its crossover signals. Use the concept of alignment and agreement. Show how VEDD AI identifies MACD signals automatically.",
    suggestedHashtags: ["#MACD", "#TradingSignals", "#Momentum", "#VEDDAi", "#IndicatorTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 11,
    title: "Multi-Timeframe Analysis",
    tradingTopic: "Timeframe Confluence",
    tradingLesson: "Analyze from higher to lower timeframes. Daily chart shows the trend, 4H shows structure, 1H shows entry. When all timeframes agree, trade confidence soars.",
    scriptureReference: "Proverbs 11:14",
    scriptureText: "Where there is no guidance, a people falls, but in an abundance of counselors there is safety.",
    devotionalMessage: "Multiple timeframes act as counselors, each offering a different perspective. Safety comes from gathering input from various sources before making decisions.",
    contentPrompt: "Share the power of multi-timeframe analysis. Explain how different timeframes provide different insights. Connect to the wisdom of seeking multiple counselors.",
    suggestedHashtags: ["#MultiTimeframe", "#Confluence", "#TradingWisdom", "#VEDDAi", "#ChartAnalysis"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 12,
    title: "Entry Strategies",
    tradingTopic: "Timing Your Entry",
    tradingLesson: "The best entries combine multiple confirmations: trend direction, support/resistance levels, indicator signals, and candlestick patterns. Patience for the perfect setup is key.",
    scriptureReference: "Habakkuk 2:3",
    scriptureText: "For still the vision awaits its appointed time; it hastens to the end—it will not lie. If it seems slow, wait for it; it will surely come; it will not delay.",
    devotionalMessage: "Wait for your trading setup like awaiting a vision's fulfillment. The best entries come to those who wait patiently for all conditions to align. Hasty entries lead to regret.",
    contentPrompt: "Create content about patience in waiting for quality trade entries. Explain confluence and multiple confirmations. Connect to waiting for God's appointed time.",
    suggestedHashtags: ["#TradeEntry", "#PatientTrading", "#Confluence", "#VEDDAi", "#QualitySetups"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 13,
    title: "Take Profit Levels",
    tradingTopic: "Exit Strategy Planning",
    tradingLesson: "Plan exits before entering. Use previous highs/lows, Fibonacci extensions, and risk-reward ratios to set take profit targets. Partial profit taking can lock in gains.",
    scriptureReference: "Luke 14:28",
    scriptureText: "For which of you, desiring to build a tower, does not first sit down and count the cost, whether he has enough to complete it?",
    devotionalMessage: "Counting the cost includes knowing when you'll exit. Plan your take profit levels before entering, just as a builder plans before breaking ground.",
    contentPrompt: "Share strategies for setting take profit levels. Explain the importance of planning exits before entries. Connect to counting the cost and planning ahead.",
    suggestedHashtags: ["#TakeProfit", "#ExitStrategy", "#TradingPlan", "#VEDDAi", "#RiskReward"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 2,
    category: "strategy"
  },
  {
    dayNumber: 14,
    title: "Week 2 Review",
    tradingTopic: "Strategy Week Summary",
    tradingLesson: "Review: Moving Averages, RSI, MACD, Multi-Timeframe Analysis, Entry Strategies, and Take Profit Planning. You now have the tools to build a complete trading strategy.",
    scriptureReference: "James 1:4",
    scriptureText: "And let steadfastness have its full effect, that you may be perfect and complete, lacking in nothing.",
    devotionalMessage: "Week 2 has added powerful tools to your arsenal. Let steadfastness in learning and practice have its full effect. You're becoming more complete as a trader.",
    contentPrompt: "Celebrate Week 2 completion! Share progress on learning technical indicators and strategy development. Encourage consistency and steady progress.",
    suggestedHashtags: ["#Week2Complete", "#StrategyDevelopment", "#TradingGrowth", "#VEDDAi", "#Progress"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 2,
    category: "review"
  },
  // Week 3: Trading Mindset
  {
    dayNumber: 15,
    title: "Trading Psychology",
    tradingTopic: "Mastering Your Mind",
    tradingLesson: "Fear and greed are the trader's biggest enemies. Fear causes early exits and missed opportunities. Greed causes overtrading and refusing to take profits. Develop emotional awareness.",
    scriptureReference: "2 Timothy 1:7",
    scriptureText: "For God gave us a spirit not of fear but of power and love and self-control.",
    devotionalMessage: "We are given power, love, and self-control - not fear. Apply this to trading: trade with confidence, respect for the market, and disciplined self-control.",
    contentPrompt: "Share about overcoming fear and greed in trading. Discuss the importance of emotional control. Connect to the spirit of power and self-control given to us.",
    suggestedHashtags: ["#TradingPsychology", "#EmotionalControl", "#FearAndGreed", "#VEDDAi", "#MindsetMatters"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 16,
    title: "Patience in Trading",
    tradingTopic: "Waiting for Quality Setups",
    tradingLesson: "Professional traders spend most of their time waiting. Quality setups don't appear constantly. Patience to wait for A+ setups separates profitable traders from the rest.",
    scriptureReference: "Isaiah 40:31",
    scriptureText: "But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary.",
    devotionalMessage: "Those who wait are renewed in strength. In trading, waiting for quality setups preserves capital and positions you for powerful moves. Wait like an eagle waiting to soar.",
    contentPrompt: "Create content about the power of patience in trading. Share how waiting for A+ setups leads to better results. Connect to waiting on the Lord for renewed strength.",
    suggestedHashtags: ["#PatientTrading", "#WaitForIt", "#QualityOverQuantity", "#VEDDAi", "#TradingMindset"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 17,
    title: "Handling Losses",
    tradingTopic: "Loss Recovery Mindset",
    tradingLesson: "Losses are tuition in the trading school. Every trader experiences them. The key is keeping losses small, learning from them, and not revenge trading. Accept losses gracefully.",
    scriptureReference: "Romans 5:3-4",
    scriptureText: "Not only that, but we rejoice in our sufferings, knowing that suffering produces endurance, and endurance produces character, and character produces hope.",
    devotionalMessage: "Losses in trading produce endurance and character when handled correctly. Don't run from losses - learn from them. They're shaping you into a better trader.",
    contentPrompt: "Share about handling trading losses with grace. Discuss learning from losses vs revenge trading. Connect to how suffering produces character and hope.",
    suggestedHashtags: ["#TradingLosses", "#LearnFromLosses", "#TradingMindset", "#VEDDAi", "#GrowthMindset"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 18,
    title: "Discipline Over Emotion",
    tradingTopic: "Following Your Trading Plan",
    tradingLesson: "Your trading plan is your north star. When emotions scream 'take this trade!' or 'hold longer!', your plan provides the objective framework for decisions. Always follow the plan.",
    scriptureReference: "Proverbs 25:28",
    scriptureText: "A man without self-control is like a city broken into and left without walls.",
    devotionalMessage: "A trader without discipline is defenseless against the market. Your trading plan is your wall of protection. Break discipline, and your account is vulnerable to attack.",
    contentPrompt: "Share about the importance of trading discipline. Discuss how a trading plan protects you. Connect to self-control as protective walls.",
    suggestedHashtags: ["#TradingDiscipline", "#TradingPlan", "#SelfControl", "#VEDDAi", "#RulesBasedTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 19,
    title: "Confidence Building",
    tradingTopic: "Trusting Your Analysis",
    tradingLesson: "Confidence comes from backtesting your strategy, keeping a trading journal, and seeing consistent results over time. Trust your analysis while remaining humble.",
    scriptureReference: "Philippians 4:13",
    scriptureText: "I can do all things through him who strengthens me.",
    devotionalMessage: "True confidence isn't arrogance - it's trusting in a strength greater than your own. Trade with confidence knowing your preparation and faith guide your path.",
    contentPrompt: "Create content about building trading confidence through preparation and practice. Discuss the balance of confidence and humility. Connect to strength through faith.",
    suggestedHashtags: ["#TradingConfidence", "#TrustYourself", "#Preparation", "#VEDDAi", "#TradingMindset"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 20,
    title: "Avoiding FOMO",
    tradingTopic: "Fear of Missing Out",
    tradingLesson: "FOMO causes traders to chase moves they missed, entering at poor levels. The market always offers new opportunities. Missing one trade doesn't mean missing all trades.",
    scriptureReference: "Proverbs 19:2",
    scriptureText: "Desire without knowledge is not good, and whoever makes haste with his feet misses his way.",
    devotionalMessage: "Hasty feet miss the way. Chasing trades you missed leads you astray from your plan. Trust that God and the market will provide new opportunities.",
    contentPrompt: "Share about overcoming FOMO in trading. Discuss how chasing missed moves leads to poor entries. Connect to the danger of hasty decisions.",
    suggestedHashtags: ["#NoFOMO", "#PatientTrading", "#DontChase", "#VEDDAi", "#TradingWisdom"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 3,
    category: "mindset"
  },
  {
    dayNumber: 21,
    title: "Week 3 Review",
    tradingTopic: "Mindset Week Summary",
    tradingLesson: "Review: Psychology, Patience, Handling Losses, Discipline, Confidence, and Avoiding FOMO. Mastering your mind is often harder than mastering charts, but equally important.",
    scriptureReference: "Romans 12:2",
    scriptureText: "Do not be conformed to this world, but be transformed by the renewal of your mind.",
    devotionalMessage: "Week 3 has been about renewing your trading mind. The transformation from emotional trader to disciplined operator is a journey. You're making progress!",
    contentPrompt: "Celebrate Week 3 - the mindset week! Share reflections on trading psychology. Encourage others on their mental game journey. Connect to mind transformation.",
    suggestedHashtags: ["#Week3Complete", "#TradingMindset", "#MentalGame", "#VEDDAi", "#Transformation"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 3,
    category: "review"
  },
  // Week 4: Execution Excellence
  {
    dayNumber: 22,
    title: "Pre-Trade Checklist",
    tradingTopic: "Trade Preparation Routine",
    tradingLesson: "Before every trade, run through your checklist: Trend direction? Key levels identified? Risk calculated? Entry trigger clear? Stop loss placed? Create and follow your personal checklist.",
    scriptureReference: "Proverbs 16:3",
    scriptureText: "Commit your work to the Lord, and your plans will be established.",
    devotionalMessage: "Commit your trading preparation to God. A diligent pre-trade routine establishes your plans and positions you for success. Preparation honors your commitment to excellence.",
    contentPrompt: "Share the importance of a pre-trade checklist. List key items to check before entering trades. Connect to committing work to God for established plans.",
    suggestedHashtags: ["#TradeChecklist", "#Preparation", "#TradingRoutine", "#VEDDAi", "#TradeSetup"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 23,
    title: "Order Types Mastery",
    tradingTopic: "Market, Limit, and Stop Orders",
    tradingLesson: "Market orders execute immediately at current price. Limit orders execute at your specified price or better. Stop orders become market orders when price reaches trigger. Use each appropriately.",
    scriptureReference: "Ecclesiastes 8:5-6",
    scriptureText: "Whoever keeps a command will know no evil thing, and the wise heart will know the proper time and the just way.",
    devotionalMessage: "Wisdom knows the proper time and way. Different order types serve different purposes. A wise trader knows when to use market vs limit vs stop orders.",
    contentPrompt: "Explain different order types and when to use each. Share practical examples. Connect to knowing the proper time and way for each action.",
    suggestedHashtags: ["#OrderTypes", "#TradingOrders", "#ExecutionTips", "#VEDDAi", "#TradingBasics"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 24,
    title: "Trade Management",
    tradingTopic: "Managing Open Positions",
    tradingLesson: "Once in a trade, management matters. Consider: trailing stops to lock in profit, partial closes at key levels, and when to let winners run vs take profit. Active management improves results.",
    scriptureReference: "Proverbs 27:23",
    scriptureText: "Know well the condition of your flocks, and give attention to your herds.",
    devotionalMessage: "A good shepherd knows their flock. A good trader knows their positions. Give attention to your open trades - they're entrusted to your care.",
    contentPrompt: "Share trade management strategies for open positions. Discuss trailing stops and partial closes. Connect to being a good steward of what's entrusted to you.",
    suggestedHashtags: ["#TradeManagement", "#OpenPositions", "#TrailingStops", "#VEDDAi", "#ActiveTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 25,
    title: "News Trading Awareness",
    tradingTopic: "Economic Calendar Impact",
    tradingLesson: "Major news events move markets violently. Know when NFP, FOMC, CPI releases happen. Either close positions before major news or factor the volatility into your strategy.",
    scriptureReference: "Proverbs 27:12",
    scriptureText: "The prudent sees danger and hides himself, but the simple go on and suffer for it.",
    devotionalMessage: "High-impact news is predictable danger on the calendar. The prudent trader either prepares for it or avoids it. Don't be caught off guard by scheduled events.",
    contentPrompt: "Share about trading around news events. Explain the importance of the economic calendar. Connect to being prudent and seeing danger ahead.",
    suggestedHashtags: ["#NewsTrading", "#EconomicCalendar", "#MarketNews", "#VEDDAi", "#TradingAwareness"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 26,
    title: "Trading Journal",
    tradingTopic: "Recording Your Trades",
    tradingLesson: "A trading journal is your personal coach. Record: entry reason, exit reason, emotions felt, what worked, what didn't. Review weekly to identify patterns in your trading.",
    scriptureReference: "Habakkuk 2:2",
    scriptureText: "And the Lord answered me: 'Write the vision; make it plain on tablets, so he may run who reads it.'",
    devotionalMessage: "Write your trading journey plainly. A journal makes patterns visible that memory would miss. Your future self will thank you for the records you keep today.",
    contentPrompt: "Share the power of keeping a trading journal. Discuss what to record and why. Connect to writing the vision and making progress visible.",
    suggestedHashtags: ["#TradingJournal", "#TradeRecords", "#SelfImprovement", "#VEDDAi", "#TradingGrowth"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 27,
    title: "Session Trading",
    tradingTopic: "Best Times to Trade",
    tradingLesson: "Different sessions have different characteristics. London/NY overlap offers highest volatility for forex. Asian session is often ranging. Match your strategy to session characteristics.",
    scriptureReference: "Ecclesiastes 3:11",
    scriptureText: "He has made everything beautiful in its time.",
    devotionalMessage: "There's a time for everything, including trading. Each session has its beauty and purpose. Find the sessions that match your strategy and lifestyle.",
    contentPrompt: "Share about trading sessions and their characteristics. Explain which sessions suit different strategies. Connect to everything being beautiful in its time.",
    suggestedHashtags: ["#TradingSessions", "#ForexSessions", "#BestTimeToTrade", "#VEDDAi", "#MarketTiming"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 4,
    category: "execution"
  },
  {
    dayNumber: 28,
    title: "Week 4 Review",
    tradingTopic: "Execution Week Summary",
    tradingLesson: "Review: Pre-Trade Checklist, Order Types, Trade Management, News Awareness, Journaling, and Session Trading. Execution excellence turns good analysis into profits.",
    scriptureReference: "James 2:17",
    scriptureText: "So also faith by itself, if it does not have works, is dead.",
    devotionalMessage: "Analysis without execution is dead. Week 4 has been about turning your knowledge into action. Faith plus works, analysis plus execution - this is the winning combination.",
    contentPrompt: "Celebrate Week 4 completion! Share about execution excellence. Discuss how good analysis requires good execution. Connect to faith requiring works.",
    suggestedHashtags: ["#Week4Complete", "#ExecutionExcellence", "#ActionTaker", "#VEDDAi", "#TradingMastery"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 4,
    category: "review"
  },
  // Week 5: Advanced Techniques
  {
    dayNumber: 29,
    title: "Fibonacci Retracements",
    tradingTopic: "Natural Market Ratios",
    tradingLesson: "Fibonacci levels (38.2%, 50%, 61.8%) often act as support/resistance. Markets tend to retrace to these levels before continuing trends. Learn to draw and trade Fibonacci levels.",
    scriptureReference: "Psalm 19:1",
    scriptureText: "The heavens declare the glory of God, and the sky above proclaims his handiwork.",
    devotionalMessage: "Fibonacci ratios appear throughout creation - in galaxies, flowers, and yes, markets. These divine proportions reflect order in apparent chaos. Trading with Fibonacci is trading with nature's design.",
    contentPrompt: "Share about Fibonacci retracements in trading. Explain how these ratios appear in nature and markets. Connect to God's handiwork visible in patterns.",
    suggestedHashtags: ["#Fibonacci", "#GoldenRatio", "#TechnicalAnalysis", "#VEDDAi", "#NaturalPatterns"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 30,
    title: "Chart Patterns",
    tradingTopic: "Head & Shoulders, Double Tops/Bottoms",
    tradingLesson: "Chart patterns signal potential reversals or continuations. Head and shoulders indicates reversal. Double tops/bottoms confirm support/resistance breaks. Triangles signal breakouts.",
    scriptureReference: "Proverbs 20:12",
    scriptureText: "The hearing ear and the seeing eye, the Lord has made them both.",
    devotionalMessage: "God gave us eyes to see patterns others miss. Train your eyes to recognize chart formations. Pattern recognition is a skill that improves with practice and intention.",
    contentPrompt: "Share about common chart patterns and what they signal. Discuss how AI helps identify patterns automatically. Connect to the gift of seeing and recognizing patterns.",
    suggestedHashtags: ["#ChartPatterns", "#PatternTrading", "#HeadAndShoulders", "#VEDDAi", "#TechnicalPatterns"],
    mediaType: "carousel",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 31,
    title: "Divergence Trading",
    tradingTopic: "Hidden and Regular Divergence",
    tradingLesson: "When price makes higher highs but indicators make lower highs, that's bearish divergence. When price makes lower lows but indicators make higher lows, that's bullish divergence. Powerful reversal signals.",
    scriptureReference: "Matthew 7:16",
    scriptureText: "You will recognize them by their fruits. Are grapes gathered from thornbushes, or figs from thistles?",
    devotionalMessage: "Divergence reveals when price action and momentum don't match - like fruit not matching the tree. Learn to recognize when the underlying reality differs from the surface appearance.",
    contentPrompt: "Explain divergence trading and its power for spotting reversals. Share examples of regular and hidden divergence. Connect to recognizing things by their true nature.",
    suggestedHashtags: ["#Divergence", "#ReversalSignals", "#RSIDivergence", "#VEDDAi", "#AdvancedTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 32,
    title: "Volume Analysis",
    tradingTopic: "Volume Confirms Price",
    tradingLesson: "Volume confirms price moves. Strong breakouts need volume. If price moves but volume is low, the move may fail. Volume spikes often mark reversals. Volume is the fuel of price movement.",
    scriptureReference: "Proverbs 20:25",
    scriptureText: "It is a snare to say rashly, 'It is holy,' and to reflect only after making vows.",
    devotionalMessage: "Don't jump into moves without confirmation. Volume validates price action. Reflect (check volume) before committing to a trade. Unconfirmed moves are traps.",
    contentPrompt: "Share the importance of volume in confirming price moves. Explain how to read volume for breakouts and reversals. Connect to confirming before committing.",
    suggestedHashtags: ["#VolumeAnalysis", "#PriceAndVolume", "#Confirmation", "#VEDDAi", "#MarketVolume"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 33,
    title: "Breakout Trading",
    tradingTopic: "Trading Range Breakouts",
    tradingLesson: "Breakouts occur when price escapes a range with momentum. Wait for the candle to close beyond the level, look for volume confirmation, and use the range height as your target.",
    scriptureReference: "Isaiah 43:19",
    scriptureText: "Behold, I am doing a new thing; now it springs forth, do you not perceive it? I am making a way in the wilderness.",
    devotionalMessage: "Breakouts represent new things springing forth. Old ranges give way to new movements. Be ready to perceive and act when new trends emerge from consolidation.",
    contentPrompt: "Share strategies for trading breakouts effectively. Discuss false breakouts and how to avoid them. Connect to new things springing forth and new opportunities.",
    suggestedHashtags: ["#BreakoutTrading", "#RangeBreakout", "#NewTrends", "#VEDDAi", "#MomentumTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 34,
    title: "Pullback Entries",
    tradingTopic: "Trading Trend Retracements",
    tradingLesson: "Rather than chasing breakouts, wait for pullbacks to key levels. Enter at the 50% retracement, at previous resistance turned support, or at the 20 EMA. Pullbacks offer better risk-reward.",
    scriptureReference: "Psalm 27:14",
    scriptureText: "Wait for the Lord; be strong, and let your heart take courage; wait for the Lord!",
    devotionalMessage: "Waiting for pullbacks requires strength and courage - courage not to chase, strength to be patient. Those who wait for the pullback often get better entries than those who chase.",
    contentPrompt: "Share the power of waiting for pullback entries. Discuss key levels for pullback entries. Connect to the courage and strength needed to wait.",
    suggestedHashtags: ["#PullbackTrading", "#PatientEntries", "#Retracements", "#VEDDAi", "#SmartEntries"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 5,
    category: "strategy"
  },
  {
    dayNumber: 35,
    title: "Week 5 Review",
    tradingTopic: "Advanced Techniques Summary",
    tradingLesson: "Review: Fibonacci, Chart Patterns, Divergence, Volume, Breakouts, and Pullbacks. These advanced techniques add precision to your trading. Combine them with fundamentals for powerful strategies.",
    scriptureReference: "Proverbs 9:9",
    scriptureText: "Give instruction to a wise man, and he will be still wiser; teach a righteous man, and he will increase in learning.",
    devotionalMessage: "Week 5 has added wisdom to wisdom. You're not just learning - you're increasing in trading knowledge. The wise continue to grow; they never stop learning.",
    contentPrompt: "Celebrate Week 5! Share advanced techniques learned. Encourage continuous learning and growth. Connect to the wise becoming wiser through instruction.",
    suggestedHashtags: ["#Week5Complete", "#AdvancedTrading", "#NeverStopLearning", "#VEDDAi", "#TradingMastery"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 5,
    category: "review"
  },
  // Week 6: AI-Powered Trading
  {
    dayNumber: 36,
    title: "AI Chart Analysis",
    tradingTopic: "Leveraging VEDD AI",
    tradingLesson: "VEDD AI analyzes charts in seconds, identifying patterns, trends, and key levels that might take you hours to find manually. Upload charts and let AI be your analysis assistant.",
    scriptureReference: "Proverbs 1:5",
    scriptureText: "Let the wise hear and increase in learning, and the one who understands obtain guidance.",
    devotionalMessage: "Wisdom seeks guidance from available resources. AI is a powerful tool that multiplies your analysis capability. Use it wisely to obtain guidance for your trading decisions.",
    contentPrompt: "Share how VEDD AI enhances chart analysis. Discuss time savings and pattern recognition accuracy. Connect to seeking and obtaining guidance from wise sources.",
    suggestedHashtags: ["#AITrading", "#VEDDAi", "#ChartAnalysis", "#SmartTrading", "#TradingTechnology"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 6,
    category: "strategy"
  },
  {
    dayNumber: 37,
    title: "Multi-Timeframe EA",
    tradingTopic: "AI-Powered Expert Advisors",
    tradingLesson: "Combine AI analysis from multiple timeframes into a single Expert Advisor. The EA bakes in pattern recognition while using live indicators for confirmation. Best of both worlds.",
    scriptureReference: "Ecclesiastes 4:9",
    scriptureText: "Two are better than one, because they have a good reward for their toil.",
    devotionalMessage: "AI analysis combined with technical indicators is better than either alone. Partnership creates synergy. Your trading benefits when multiple tools work together.",
    contentPrompt: "Share how multi-timeframe EAs combine AI and technical analysis. Discuss the synergy of multiple confirmations. Connect to two being better than one.",
    suggestedHashtags: ["#ExpertAdvisor", "#MultiTimeframe", "#AIandTA", "#VEDDAi", "#AutomatedTrading"],
    mediaType: "video",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 6,
    category: "strategy"
  },
  {
    dayNumber: 38,
    title: "News Sentiment Analysis",
    tradingTopic: "AI News Impact Assessment",
    tradingLesson: "AI analyzes financial news and assigns sentiment scores. When news sentiment aligns with your technical signal, confidence increases. When they conflict, exercise caution.",
    scriptureReference: "Proverbs 18:15",
    scriptureText: "An intelligent heart acquires knowledge, and the ear of the wise seeks knowledge.",
    devotionalMessage: "The wise seek knowledge from all available sources. News sentiment adds another layer of information to your analysis. Be wise - gather and weigh multiple inputs.",
    contentPrompt: "Share how AI news analysis enhances trading decisions. Discuss sentiment alignment with technical signals. Connect to seeking knowledge from multiple sources.",
    suggestedHashtags: ["#NewsSentiment", "#AIAnalysis", "#MarketNews", "#VEDDAi", "#SmartDecisions"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 6,
    category: "strategy"
  },
  {
    dayNumber: 39,
    title: "ATR-Based Stop Loss",
    tradingTopic: "Volatility-Adjusted Protection",
    tradingLesson: "ATR (Average True Range) measures market volatility. BTC moves differently than EURUSD. ATR-based stops automatically adjust to each asset's typical movement, preventing unnecessary stop-outs.",
    scriptureReference: "Proverbs 14:8",
    scriptureText: "The wisdom of the prudent is to discern his way, but the folly of fools is deceiving.",
    devotionalMessage: "Prudent traders discern the unique nature of each market. What works for forex may not work for crypto. ATR helps you adapt your approach to each instrument's character.",
    contentPrompt: "Share how ATR-based stops adapt to different market volatility. Explain why fixed pip stops don't work for all pairs. Connect to prudently discerning the way for each market.",
    suggestedHashtags: ["#ATRStops", "#VolatilityTrading", "#AdaptiveStops", "#VEDDAi", "#SmartRisk"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 6,
    category: "strategy"
  },
  {
    dayNumber: 40,
    title: "Live AI Refresh",
    tradingTopic: "Keeping Analysis Current",
    tradingLesson: "Markets evolve constantly. Live AI Refresh monitors your EA's symbols for pattern changes, alerting you when conditions shift significantly. Stay informed without constant chart watching.",
    scriptureReference: "1 Thessalonians 5:6",
    scriptureText: "So then let us not sleep, as others do, but let us keep awake and be sober.",
    devotionalMessage: "Stay awake and vigilant in the markets. Live AI Refresh keeps watch when you can't. It's your digital watchman, alerting you to significant changes.",
    contentPrompt: "Share how Live AI Refresh keeps your analysis current. Discuss the benefit of automated pattern monitoring. Connect to staying awake and vigilant.",
    suggestedHashtags: ["#LiveRefresh", "#AIMonitoring", "#StayVigilant", "#VEDDAi", "#ActiveTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 6,
    category: "strategy"
  },
  {
    dayNumber: 41,
    title: "What-If Analysis",
    tradingTopic: "AI Scenario Planning",
    tradingLesson: "Before entering trades, explore 'what if' scenarios. What if price hits target? What if stop is hit? What if news changes sentiment? AI scenario analysis helps you prepare for multiple outcomes.",
    scriptureReference: "Luke 14:31",
    scriptureText: "Or what king, going out to encounter another king in war, will not sit down first and deliberate whether he is able with ten thousand to meet him who comes against him with twenty thousand?",
    devotionalMessage: "Wise kings count the cost before battle. Wise traders consider scenarios before entering. What-if analysis is your strategic planning before the trade war begins.",
    contentPrompt: "Share the value of what-if scenario analysis before trading. Discuss exploring different outcomes. Connect to deliberating and counting the cost before action.",
    suggestedHashtags: ["#ScenarioAnalysis", "#WhatIfTrading", "#RiskPlanning", "#VEDDAi", "#StrategicTrading"],
    mediaType: "image",
    tokenReward: 15,
    bonusTokens: 5,
    weekNumber: 6,
    category: "strategy"
  },
  {
    dayNumber: 42,
    title: "Week 6 Review",
    tradingTopic: "AI Trading Week Summary",
    tradingLesson: "Review: AI Analysis, Multi-TF EAs, News Sentiment, ATR Stops, Live Refresh, and What-If Analysis. You've learned to leverage AI as your trading partner. Technology amplifies human wisdom.",
    scriptureReference: "Daniel 12:4",
    scriptureText: "But you, Daniel, shut up the words and seal the book, until the time of the end. Many shall run to and fro, and knowledge shall increase.",
    devotionalMessage: "We live in a time of increasing knowledge and technology. AI tools were once science fiction; now they're your trading partners. Embrace these tools while grounding decisions in timeless wisdom.",
    contentPrompt: "Celebrate Week 6! Share how AI has enhanced your trading approach. Discuss the balance of technology and wisdom. Connect to increasing knowledge in our times.",
    suggestedHashtags: ["#Week6Complete", "#AITrading", "#TechAndWisdom", "#VEDDAi", "#FutureOfTrading"],
    mediaType: "carousel",
    tokenReward: 20,
    bonusTokens: 10,
    weekNumber: 6,
    category: "review"
  },
  // Final Days: Integration & Graduation
  {
    dayNumber: 43,
    title: "Your Trading System",
    tradingTopic: "Putting It All Together",
    tradingLesson: "You now have all the pieces. Combine: foundation (S/R, trends), strategy (indicators, patterns), mindset (discipline, patience), execution (checklists, journals), and AI tools. This is YOUR system.",
    scriptureReference: "1 Corinthians 3:10",
    scriptureText: "According to the grace of God given to me, like a skilled master builder I laid a foundation, and someone else is building upon it.",
    devotionalMessage: "You are now a builder, constructing your unique trading system on the foundation laid over 43 days. Build wisely, with intention, and according to your design.",
    contentPrompt: "Share your journey of building a complete trading system. Discuss how all the pieces fit together. Connect to being a skilled builder on a solid foundation.",
    suggestedHashtags: ["#TradingSystem", "#CompleteTrader", "#BuiltToLast", "#VEDDAi", "#TradingSuccess"],
    mediaType: "carousel",
    tokenReward: 25,
    bonusTokens: 15,
    weekNumber: 7,
    category: "review"
  },
  {
    dayNumber: 44,
    title: "Graduation Day",
    tradingTopic: "Ambassador Certification Complete",
    tradingLesson: "Congratulations! You've completed the 44-day Ambassador Content Journey. You're now equipped to trade with wisdom, use AI tools effectively, and share your knowledge with others. Welcome to the VEDD AI family!",
    scriptureReference: "2 Timothy 4:7",
    scriptureText: "I have fought the good fight, I have finished the race, I have kept the faith.",
    devotionalMessage: "You've fought through 44 days, finished this race, and kept faith in your trading journey. This isn't the end - it's a new beginning. Go forth as an ambassador of wise, AI-enhanced trading!",
    contentPrompt: "Celebrate completing the 44-day journey! Share your transformation and key lessons learned. Inspire others to start their journey. Connect to finishing the race and keeping faith.",
    suggestedHashtags: ["#GraduationDay", "#44DayJourney", "#VEDDAmabassador", "#VEDDAi", "#TradingSuccess", "#JourneyComplete"],
    mediaType: "video",
    tokenReward: 50,
    bonusTokens: 25,
    weekNumber: 7,
    category: "review"
  }
];

export default ambassadorContentCurriculum;
