// AUTO-GENERATED by scripts/gen-build-info.mjs at build time. Do not edit.
export const BUILD_COMMIT = "f22ab22f-dirty";
export const BUILD_BRANCH = "main";
export const BUILT_AT = "2026-09-20T00:37:40.670Z";
