// AUTO-GENERATED by scripts/gen-build-info.mjs at build time. Do not edit.
export const BUILD_COMMIT = "1d104f67-dirty";
export const BUILD_BRANCH = "main";
export const BUILT_AT = "2026-10-05T01:33:05.079Z";
