// AUTO-GENERATED by scripts/gen-build-info.mjs at build time. Do not edit.
export const BUILD_COMMIT = "306254af-dirty";
export const BUILD_BRANCH = "main";
export const BUILT_AT = "2026-09-20T18:06:41.582Z";
