import { ChartAnalysisResponse } from "@shared/types";

interface TimeframeAnalysisData {
  timeframe: string;
  analysis: ChartAnalysisResponse;
}

/**
 * Generate MT5 EA (Expert Advisor) code based on multi-timeframe analysis
 */
export function generateMT5EACode(
  symbol: string,
  timeframes: TimeframeAnalysisData[]
): string {
  // Sort timeframes from smallest to largest
  const sortedTimeframes = [...timeframes].sort((a, b) => {
    const order = ['M1', 'M5', 'M15', 'M30', 'H1', 'H4', 'D1', 'W1'];
    return order.indexOf(a.timeframe) - order.indexOf(b.timeframe);
  });

  const primaryTF = sortedTimeframes[0];
  const higherTFs = sortedTimeframes.slice(1);

  // Extract entry conditions from analyses
  const buyConditions: string[] = [];
  const sellConditions: string[] = [];

  sortedTimeframes.forEach((tf, index) => {
    const tfVar = tf.timeframe.replace(/\D/g, '');
    const isBuy = tf.analysis.direction?.toUpperCase() === 'BUY';
    const isSell = tf.analysis.direction?.toUpperCase() === 'SELL';

    if (isBuy) {
      buyConditions.push(`tf${tfVar}_trend_bullish`);
    }
    if (isSell) {
      sellConditions.push(`tf${tfVar}_trend_bearish`);
    }
  });

  // Get ATR-based stop loss if available
  const atrStopLoss = primaryTF.analysis.atrStopLoss?.recommended || primaryTF.analysis.stopLoss;
  const takeProfit = primaryTF.analysis.takeProfit || "Unknown";

  const code = `//+------------------------------------------------------------------+
//|                                         Multi-Timeframe EA.mq5 |
//|                        Generated by VEDD Chart Analysis Tool    |
//|                                             https://vedd.io     |
//+------------------------------------------------------------------+
#property copyright "Generated by VEDD"
#property link      "https://vedd.io"
#property version   "1.00"

//--- Input parameters
input double LotSize = 0.01;                    // Lot size
input double StopLossPips = 50;                 // Stop loss in pips (ATR-based recommended: ${atrStopLoss})
input double TakeProfitPips = 100;              // Take profit in pips (Recommended: ${takeProfit})
input int RSI_Period = 14;                      // RSI period
input int RSI_Overbought = 70;                  // RSI overbought level
input int RSI_Oversold = 30;                    // RSI oversold level
input int MACD_FastEMA = 12;                    // MACD Fast EMA
input int MACD_SlowEMA = 26;                    // MACD Slow EMA
input int MACD_SignalSMA = 9;                   // MACD Signal SMA
input bool UseATR_StopLoss = true;              // Use ATR-based stop loss
input double ATR_Multiplier = 1.5;              // ATR multiplier for stop loss

//--- Global variables
int rsi_handle, macd_handle, atr_handle;
double rsi_buffer[], macd_main[], macd_signal[], atr_buffer[];

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   //--- Initialize indicators
   rsi_handle = iRSI(_Symbol, PERIOD_CURRENT, RSI_Period, PRICE_CLOSE);
   macd_handle = iMACD(_Symbol, PERIOD_CURRENT, MACD_FastEMA, MACD_SlowEMA, MACD_SignalSMA, PRICE_CLOSE);
   atr_handle = iATR(_Symbol, PERIOD_CURRENT, 14);
   
   if(rsi_handle == INVALID_HANDLE || macd_handle == INVALID_HANDLE || atr_handle == INVALID_HANDLE)
   {
      Print("Error creating indicators");
      return(INIT_FAILED);
   }
   
   ArraySetAsSeries(rsi_buffer, true);
   ArraySetAsSeries(macd_main, true);
   ArraySetAsSeries(macd_signal, true);
   ArraySetAsSeries(atr_buffer, true);
   
   Print("Multi-Timeframe EA initialized for ${symbol}");
   Print("Analyzing timeframes: ${sortedTimeframes.map(tf => tf.timeframe).join(', ')}");
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   IndicatorRelease(rsi_handle);
   IndicatorRelease(macd_handle);
   IndicatorRelease(atr_handle);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   //--- Check if a new bar has formed
   static datetime last_bar_time = 0;
   datetime current_bar_time = iTime(_Symbol, PERIOD_CURRENT, 0);
   
   if(current_bar_time == last_bar_time)
      return;
   
   last_bar_time = current_bar_time;
   
   //--- Copy indicator values
   if(CopyBuffer(rsi_handle, 0, 0, 3, rsi_buffer) <= 0) return;
   if(CopyBuffer(macd_handle, 0, 0, 3, macd_main) <= 0) return;
   if(CopyBuffer(macd_handle, 1, 0, 3, macd_signal) <= 0) return;
   if(CopyBuffer(atr_handle, 0, 0, 3, atr_buffer) <= 0) return;
   
   //--- Check multi-timeframe conditions
   bool tf${sortedTimeframes[0].timeframe.replace(/\D/g, '')}_trend_bullish = CheckBullishCondition();
   bool tf${sortedTimeframes[0].timeframe.replace(/\D/g, '')}_trend_bearish = CheckBearishCondition();
   
${higherTFs.map(tf => `   bool tf${tf.timeframe.replace(/\D/g, '')}_trend_bullish = CheckHigherTimeframeTrend("${tf.timeframe}", true);
   bool tf${tf.timeframe.replace(/\D/g, '')}_trend_bearish = CheckHigherTimeframeTrend("${tf.timeframe}", false);`).join('\n')}
   
   //--- Entry conditions based on multi-timeframe analysis
   bool buy_signal = ${buyConditions.length > 0 ? buyConditions.join(' && ') : 'false'};
   bool sell_signal = ${sellConditions.length > 0 ? sellConditions.join(' && ') : 'false'};
   
   //--- Volume confirmation
   bool volume_confirmed = CheckVolumeConfirmation();
   
   //--- Execute trades
   if(buy_signal && volume_confirmed && PositionsTotal() == 0)
   {
      double sl = UseATR_StopLoss ? CalculateATR_StopLoss(true) : 0;
      double tp = UseATR_StopLoss ? CalculateATR_TakeProfit(true) : 0;
      OpenBuyPosition(sl, tp);
   }
   else if(sell_signal && volume_confirmed && PositionsTotal() == 0)
   {
      double sl = UseATR_StopLoss ? CalculateATR_StopLoss(false) : 0;
      double tp = UseATR_StopLoss ? CalculateATR_TakeProfit(false) : 0;
      OpenSellPosition(sl, tp);
   }
}

//+------------------------------------------------------------------+
//| Check bullish condition on current timeframe                     |
//+------------------------------------------------------------------+
bool CheckBullishCondition()
{
   //--- RSI oversold
   if(rsi_buffer[0] < RSI_Oversold)
      return false;
   
   //--- MACD bullish crossover
   bool macd_bullish = macd_main[0] > macd_signal[0] && macd_main[1] <= macd_signal[1];
   
   //--- Volume increasing (simplified check)
   bool volume_ok = true; // Implement volume check if available
   
   return macd_bullish && volume_ok;
}

//+------------------------------------------------------------------+
//| Check bearish condition on current timeframe                     |
//+------------------------------------------------------------------+
bool CheckBearishCondition()
{
   //--- RSI overbought
   if(rsi_buffer[0] > RSI_Overbought)
      return true;
   
   //--- MACD bearish crossover
   bool macd_bearish = macd_main[0] < macd_signal[0] && macd_main[1] >= macd_signal[1];
   
   return macd_bearish;
}

//+------------------------------------------------------------------+
//| Check higher timeframe trend                                     |
//+------------------------------------------------------------------+
bool CheckHigherTimeframeTrend(string timeframe, bool check_bullish)
{
   ENUM_TIMEFRAMES tf = StringToTimeframe(timeframe);
   int htf_macd = iMACD(_Symbol, tf, MACD_FastEMA, MACD_SlowEMA, MACD_SignalSMA, PRICE_CLOSE);
   double htf_macd_main[], htf_macd_signal[];
   
   ArraySetAsSeries(htf_macd_main, true);
   ArraySetAsSeries(htf_macd_signal, true);
   
   if(CopyBuffer(htf_macd, 0, 0, 2, htf_macd_main) <= 0) return false;
   if(CopyBuffer(htf_macd, 1, 0, 2, htf_macd_signal) <= 0) return false;
   
   IndicatorRelease(htf_macd);
   
   if(check_bullish)
      return htf_macd_main[0] > htf_macd_signal[0];
   else
      return htf_macd_main[0] < htf_macd_signal[0];
}

//+------------------------------------------------------------------+
//| Check volume confirmation                                        |
//+------------------------------------------------------------------+
bool CheckVolumeConfirmation()
{
   long volume[];
   ArraySetAsSeries(volume, true);
   
   if(CopyTickVolume(_Symbol, PERIOD_CURRENT, 0, 3, volume) <= 0)
      return true; // Default to true if volume data unavailable
   
   //--- Current volume should be higher than average of last 2 bars
   return volume[0] > (volume[1] + volume[2]) / 2;
}

//+------------------------------------------------------------------+
//| Calculate ATR-based stop loss                                    |
//+------------------------------------------------------------------+
double CalculateATR_StopLoss(bool is_buy)
{
   double atr = atr_buffer[0];
   double current_price = is_buy ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double stop_distance = atr * ATR_Multiplier;
   
   if(is_buy)
      return NormalizeDouble(current_price - stop_distance, _Digits);
   else
      return NormalizeDouble(current_price + stop_distance, _Digits);
}

//+------------------------------------------------------------------+
//| Calculate ATR-based take profit                                  |
//+------------------------------------------------------------------+
double CalculateATR_TakeProfit(bool is_buy)
{
   double atr = atr_buffer[0];
   double current_price = is_buy ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) : SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double profit_distance = atr * ATR_Multiplier * 2; // 2:1 risk-reward
   
   if(is_buy)
      return NormalizeDouble(current_price + profit_distance, _Digits);
   else
      return NormalizeDouble(current_price - profit_distance, _Digits);
}

//+------------------------------------------------------------------+
//| Open buy position                                                |
//+------------------------------------------------------------------+
void OpenBuyPosition(double sl, double tp)
{
   MqlTradeRequest request = {};
   MqlTradeResult result = {};
   
   double price = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   
   request.action = TRADE_ACTION_DEAL;
   request.symbol = _Symbol;
   request.volume = LotSize;
   request.type = ORDER_TYPE_BUY;
   request.price = price;
   request.sl = sl;
   request.tp = tp;
   request.deviation = 10;
   request.magic = 123456;
   request.comment = "Multi-TF EA Buy";
   
   if(OrderSend(request, result))
      Print("Buy order opened successfully at ", price);
   else
      Print("Error opening buy order: ", GetLastError());
}

//+------------------------------------------------------------------+
//| Open sell position                                               |
//+------------------------------------------------------------------+
void OpenSellPosition(double sl, double tp)
{
   MqlTradeRequest request = {};
   MqlTradeResult result = {};
   
   double price = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   
   request.action = TRADE_ACTION_DEAL;
   request.symbol = _Symbol;
   request.volume = LotSize;
   request.type = ORDER_TYPE_SELL;
   request.price = price;
   request.sl = sl;
   request.tp = tp;
   request.deviation = 10;
   request.magic = 123456;
   request.comment = "Multi-TF EA Sell";
   
   if(OrderSend(request, result))
      Print("Sell order opened successfully at ", price);
   else
      Print("Error opening sell order: ", GetLastError());
}

//+------------------------------------------------------------------+
//| Convert string to timeframe enum                                 |
//+------------------------------------------------------------------+
ENUM_TIMEFRAMES StringToTimeframe(string tf)
{
   if(tf == "M1") return PERIOD_M1;
   if(tf == "M5") return PERIOD_M5;
   if(tf == "M15") return PERIOD_M15;
   if(tf == "M30") return PERIOD_M30;
   if(tf == "H1") return PERIOD_H1;
   if(tf == "H4") return PERIOD_H4;
   if(tf == "D1") return PERIOD_D1;
   if(tf == "W1") return PERIOD_W1;
   return PERIOD_CURRENT;
}
//+------------------------------------------------------------------+
`;

  return code;
}

/**
 * Generate TradingView Pine Script code based on multi-timeframe analysis
 */
export function generateTradingViewCode(
  symbol: string,
  timeframes: TimeframeAnalysisData[]
): string {
  const sortedTimeframes = [...timeframes].sort((a, b) => {
    const order = ['M1', 'M5', 'M15', 'M30', 'H1', 'H4', 'D1', 'W1'];
    return order.indexOf(a.timeframe) - order.indexOf(b.timeframe);
  });

  const primaryTF = sortedTimeframes[0];
  const atrStopLoss = primaryTF.analysis.atrStopLoss?.atrValue || "0.0010";

  const code = `//@version=5
strategy("Multi-Timeframe Strategy - ${symbol}", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=10)

// ============================================================================
// GENERATED BY VEDD CHART ANALYSIS TOOL
// https://vedd.io
// ============================================================================

// Input Parameters
lot_size = input.float(0.01, "Lot Size", minval=0.01, step=0.01)
use_atr_sl = input.bool(true, "Use ATR-based Stop Loss")
atr_multiplier = input.float(1.5, "ATR Multiplier", minval=0.5, step=0.1)
rsi_period = input.int(14, "RSI Period", minval=1)
rsi_overbought = input.int(70, "RSI Overbought", minval=50, maxval=100)
rsi_oversold = input.int(30, "RSI Oversold", minval=0, maxval=50)

// Indicator Calculations
rsi = ta.rsi(close, rsi_period)
[macd_line, signal_line, _] = ta.macd(close, 12, 26, 9)
atr = ta.atr(14)

// Multi-Timeframe Analysis
${sortedTimeframes.map((tf, index) => {
  const tfPine = tf.timeframe.replace('M', '').replace('H', '60').replace('D', '1D').replace('W', '1W');
  const isBuy = tf.analysis.direction?.toUpperCase() === 'BUY';
  const isSell = tf.analysis.direction?.toUpperCase() === 'SELL';
  
  return `// ${tf.timeframe} Timeframe
tf_${tf.timeframe}_macd = request.security(syminfo.tickerid, "${tfPine === tf.timeframe ? tf.timeframe.toLowerCase() : tfPine}", macd_line)
tf_${tf.timeframe}_signal = request.security(syminfo.tickerid, "${tfPine === tf.timeframe ? tf.timeframe.toLowerCase() : tfPine}", signal_line)
tf_${tf.timeframe}_bullish = tf_${tf.timeframe}_macd > tf_${tf.timeframe}_signal ${isBuy ? '// Buy signal detected' : ''}
tf_${tf.timeframe}_bearish = tf_${tf.timeframe}_macd < tf_${tf.timeframe}_signal ${isSell ? '// Sell signal detected' : ''}`;
}).join('\n\n')}

// Volume Confirmation
volume_confirmed = volume > ta.sma(volume, 20)

// Entry Conditions
buy_condition = ${sortedTimeframes.filter(tf => tf.analysis.direction?.toUpperCase() === 'BUY').map(tf => `tf_${tf.timeframe}_bullish`).join(' and ')} and volume_confirmed and rsi < 70
sell_condition = ${sortedTimeframes.filter(tf => tf.analysis.direction?.toUpperCase() === 'SELL').map(tf => `tf_${tf.timeframe}_bearish`).join(' and ')} and volume_confirmed and rsi > 30

// ATR-based Stop Loss and Take Profit
atr_stop_distance = atr * atr_multiplier
atr_tp_distance = atr * atr_multiplier * 2.0 // 2:1 risk-reward

// Execute Trades
if buy_condition and strategy.position_size == 0
    stop_loss = use_atr_sl ? close - atr_stop_distance : na
    take_profit = use_atr_sl ? close + atr_tp_distance : na
    strategy.entry("Long", strategy.long)
    if use_atr_sl
        strategy.exit("Exit Long", "Long", stop=stop_loss, limit=take_profit)

if sell_condition and strategy.position_size == 0
    stop_loss = use_atr_sl ? close + atr_stop_distance : na
    take_profit = use_atr_sl ? close - atr_tp_distance : na
    strategy.entry("Short", strategy.short)
    if use_atr_sl
        strategy.exit("Exit Short", "Short", stop=stop_loss, limit=take_profit)

// Plot Indicators
plot(rsi, "RSI", color=color.blue)
hline(rsi_overbought, "Overbought", color=color.red, linestyle=hline.style_dashed)
hline(rsi_oversold, "Oversold", color=color.green, linestyle=hline.style_dashed)

// Plot Buy/Sell Signals
plotshape(buy_condition, "Buy Signal", shape.triangleup, location.belowbar, color.green, size=size.small)
plotshape(sell_condition, "Sell Signal", shape.triangledown, location.abovebar, color.red, size=size.small)

// ============================================================================
// STRATEGY NOTES:
// - This strategy combines ${sortedTimeframes.length} timeframes: ${sortedTimeframes.map(tf => tf.timeframe).join(', ')}
// - Uses ATR-based stops with ${atrStopLoss} average range
// - Includes volume and momentum confirmation
// - Risk-Reward Ratio: 1:2 (configurable)
// ============================================================================
`;

  return code;
}
